Adjust update-initramfs.conf

diff --git a/build-armbian/armbian-files/common-files/etc/initramfs/post-update.d/99-uboot b/build-armbian/armbian-files/common-files/etc/initramfs/post-update.d/99-uboot
--- a/build-armbian/armbian-files/common-files/etc/initramfs/post-update.d/99-uboot
+++ b/build-armbian/armbian-files/common-files/etc/initramfs/post-update.d/99-uboot
@@ -6,21 +6,21 @@ K_VER="$1"
 INITRD_FILE="/boot/initrd.img-${K_VER}"
 UINITRD_FILE="/boot/uInitrd-${K_VER}"
 
-echo "update-initramfs: fnnas: Converting to u-boot format: ${UINITRD_FILE}..." >&2
+echo "update-initramfs: Armbian: Converting to u-boot format: ${UINITRD_FILE}..." >&2
 [ -f "${INITRD_FILE}" ] || {
-    echo "update-initramfs: fnnas: ERROR: initrd not found: ${INITRD_FILE}" >&2
+    echo "update-initramfs: Armbian: ERROR: initrd not found: ${INITRD_FILE}" >&2
     exit 0
 }
-if ! mkimage -A arm64 -O linux -T ramdisk -C none -n uInitrd -d "${INITRD_FILE}" "${UINITRD_FILE}"; then
-    echo "update-initramfs: fnnas: ERROR: mkimage failed!" >&2
+if ! mkimage -A arm64 -O linux -T ramdisk -C gzip -n uInitrd -d "${INITRD_FILE}" "${UINITRD_FILE}"; then
+    echo "update-initramfs: Armbian: ERROR: mkimage failed!" >&2
     exit 0
 fi
 
 # Create symlink to uInitrd for bootloader, fall back to copy if symlink fails
 ln -sfn "$(basename "${UINITRD_FILE}")" /boot/uInitrd 2>/dev/null || {
     echo "Symlink failed, falling back to copy." >&2
-    cp -fv "${UINITRD_FILE}" /boot/uInitrd
+    cp -vf "${UINITRD_FILE}" /boot/uInitrd
 }
 
-echo "update-initramfs: fnnas: done." >&2
+echo "update-initramfs: Armbian: done." >&2
 exit 0
