armbian-update: Optimize kernel update script

diff --git a/build-armbian/armbian-files/common-files/usr/sbin/armbian-update b/build-armbian/armbian-files/common-files/usr/sbin/armbian-update
--- a/build-armbian/armbian-files/common-files/usr/sbin/armbian-update
+++ b/build-armbian/armbian-files/common-files/usr/sbin/armbian-update
@@ -66,7 +66,7 @@ error_msg() {
 
 # Check dependencies
 check_depends() {
-    echo -e "${STEPS} Starting to check dependencies..."
+    echo -e "${STEPS} Start checking dependencies..."
 
     is_missing="0"
     necessary_packages=("subversion" "tar" "coreutils" "bsdextrautils" "jq")
@@ -77,15 +77,27 @@ check_depends() {
     done
 
     if [[ "${is_missing}" -eq "1" ]]; then
-        echo -e "${INFO} Starting to install dependencies..."
+        echo -e "${INFO} Start installing dependencies..."
         sudo apt-get update
         sudo apt-get install -y ${necessary_packages[*]}
-        [[ "${?}" -ne "0" ]] && error_msg "Dependency installation failed, stop update."
+        [[ "${?}" -ne "0" ]] && error_msg "Dependency installation failed, stop updating."
     else
         echo -e "${INFO} Dependency check completed."
     fi
 
     sync && echo ""
+}
+
+# Checking network
+check_network() {
+    echo -e "${STEPS} Start checking network status..."
+
+    # Download from Chinese mirrors, check the status of connecting to the Chinese network
+    curl --connect-timeout 10 -s "myip.ipip.net" 2>/dev/null | grep -qo "中国" && cn_net="yes" || cn_net="no"
+
+    # Download from github.com, check the status of connection to github.com
+    curl --connect-timeout 10 -s "github.com" >/dev/null 2>&1 && github_net="yes" || github_net="no"
+    [[ "${github_net}" == "yes" ]] || error_msg "Your network cannot access [ github.com ], unable to download the kernel."
 }
 
 # Get kernel TEXT_OFFSET, For u-boot.ext and u-boot.emmc
@@ -102,19 +114,9 @@ get_textoffset() {
     [[ "$(hexdump -n 15 -x "${temp_dir}/${vmlinuz_name}" 2>/dev/null | head -n 1 | awk '{print $7}')" == "0108" ]] && need_overload="no"
 }
 
-# Checking network
-check_network() {
-    # Download from Chinese mirrors, check the status of connecting to the Chinese network
-    curl --connect-timeout 10 -s "myip.ipip.net" 2>/dev/null | grep -qo "中国" && cn_net="yes" || cn_net="no"
-
-    # Download from github.com, check the status of connection to github.com
-    curl --connect-timeout 10 -s "github.com" >/dev/null 2>&1 && github_net="yes" || github_net="no"
-    [[ "${github_net}" == "yes" ]] || error_msg "Your network cannot access [ github.com ], unable to download the kernel."
-}
-
 # Initialize all variables
 init_var() {
-    echo -e "${STEPS} Starting to initialize environment..."
+    echo -e "${STEPS} Start initializing parameters..."
 
     # Check release file
     [[ -f "${ophub_release_file}" ]] || error_msg "missing [ ${ophub_release_file} ] file."
@@ -193,6 +195,7 @@ init_var() {
 
     # Complete URL
     [[ -n "${GITHUB_CDN}" && "${GITHUB_CDN:0-1}" != "/" ]] && GITHUB_CDN="${GITHUB_CDN}/"
+    #[[ -z "${GITHUB_CDN}" && cn_net="yes" ]] && GITHUB_CDN="https://gh...xy.com/"
 
     # Adjust the custom kernel repository url format
     [[ -z "${KERNEL_REPO}" ]] && KERNEL_REPO="ophub/kernel"
@@ -227,10 +230,10 @@ init_var() {
         DISK_NAME="${ROOT_PTNAME:0:-2}"
         ;;
     *)
-        error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+        error_msg "Unrecognized disk type ${ROOT_PTNAME}!"
         ;;
     esac
-    echo -e "${INFO} Armbian running: [ /dev/${DISK_NAME} ]"
+    echo -e "${INFO} Armbian is running on: [ /dev/${DISK_NAME} ]"
 
     sync && echo ""
 }
@@ -238,7 +241,7 @@ init_var() {
 # Query the latest kernel version
 query_version() {
     cd ${current_path}
-    echo -e "${STEPS} Starting to query kernel version..."
+    echo -e "${STEPS} Start querying kernel version..."
 
     # Query the current version
     current_kernel_signature="$(uname -r)"
@@ -267,7 +270,6 @@ query_version() {
 
     # Query the latest kernel version
     [[ -z "${inputs_kernel}" ]] && {
-        check_network
         latest_version="$(
             curl -s -H "Accept: application/vnd.github+json" \
                 ${kernel_api}/releases/tags/kernel_${KERNEL_TAGS} |
@@ -301,23 +303,22 @@ query_version() {
 # Download the kernel
 download_kernel() {
     cd ${current_path}
-    echo -e "${STEPS} Starting to download kernel packages..."
+    echo -e "${STEPS} Start downloading kernel package..."
 
     # Download kernel
     if [[ "$(ls ${kernel_path}/*-${inputs_kernel}-*.tar.gz -l 2>/dev/null | grep "^-" | wc -l)" -lt "4" ]]; then
         # Download the kernel from [ releases ]
-        # [[ "${cn_net}" == "yes" ]] && kernel_down_from="${china_mirrors}"
         kernel_down_from="${GITHUB_CDN}https://github.com/${KERNEL_REPO}/releases/download/kernel_${KERNEL_TAGS}/${inputs_kernel}.tar.gz"
 
-        echo -e "${INFO} Start downloading the kernel from [ ${kernel_down_from} ]"
-        echo -e "${INFO} Download the kernel files to the temporary directory: [ ${kernel_path} ]"
+        echo -e "${INFO} Start downloading kernel from [ ${kernel_down_from} ]"
+        echo -e "${INFO} Download kernel to temporary directory: [ ${kernel_path} ]"
         wget "${kernel_down_from}" -q -P "${kernel_path}"
-        [[ "${?}" -ne "0" ]] && error_msg "Failed to download the kernel files from the server."
+        [[ "${?}" -ne "0" ]] && error_msg "Failed to download kernel from server."
         tar -xf "${kernel_path}/${inputs_kernel}.tar.gz" -C "${kernel_path}"
-        [[ "${?}" -ne "0" ]] && error_msg "[ ${inputs_kernel} ] kernel decompression failed, stop updating."
+        [[ "${?}" -ne "0" ]] && error_msg "Failed to extract kernel [ ${inputs_kernel} ], stop updating."
         kernel_path="${kernel_path}/${inputs_kernel}"
     else
-        echo -e "${INFO} Use local kernel: [ ${inputs_kernel} ]"
+        echo -e "${INFO} Using local kernel package: [ ${inputs_kernel} ]"
     fi
 
     sync && echo ""
@@ -326,7 +327,7 @@ download_kernel() {
 # Check kernel files list
 check_kernel() {
     cd ${kernel_path}
-    echo -e "${STEPS} Starting to check kernel packages..."
+    echo -e "${STEPS} Start checking kernel package..."
 
     # Determine custom kernel filename
     kernel_boot="$(ls boot-${inputs_kernel}-*.tar.gz 2>/dev/null | head -n 1)"
@@ -338,7 +339,7 @@ check_kernel() {
     # Check if the file is added with TEXT_OFFSET patch
     [[ "${PLATFORM}" == "amlogic" ]] && {
         get_textoffset "${kernel_path}/${kernel_boot}" "vmlinuz-${kernel_name}"
-        echo -e "${INFO} Need to use overload: [ ${need_overload} ]"
+        echo -e "${INFO} Overload is required: [ ${need_overload} ]"
         if [[ "${need_overload}" == "yes" ]]; then
             [[ -n "${UBOOT_OVERLOAD}" && -f "/boot/${UBOOT_OVERLOAD}" ]] || error_msg "The UBOOT_OVERLOAD file is missing and cannot be update."
         fi
@@ -350,7 +351,7 @@ check_kernel() {
     [[ -s "${sha256sums_file}" && -n "$(cat ${sha256sums_file})" ]] || sha256sums_check="0"
     # Loop check file
     [[ "${sha256sums_check}" -eq "1" ]] && {
-        echo -e "${INFO} Starting sha256sum check..."
+        echo -e "${INFO} Start performing sha256sum check..."
 
         kernel_list=("boot" "dtb-${PLATFORM}" "header" "modules")
         i="1"
@@ -373,7 +374,7 @@ check_kernel() {
 
 # Backup current kernel
 backup_kernel() {
-    echo -e "${STEPS} Starting to backup the current kernel packages..."
+    echo -e "${STEPS} Start backing up current kernel..."
 
     [[ -d "${backup_path}" ]] || mkdir -p ${backup_path}
     rm -rf ${backup_path}/${current_kernel}
@@ -441,7 +442,7 @@ backup_kernel() {
 # Update the kernel
 update_kernel() {
     cd ${kernel_path}
-    echo -e "${STEPS} Starting to unpack kernel packages..."
+    echo -e "${STEPS} Start unpacking kernel..."
 
     # Delete the current kernel files
     rm -f /boot/config-* /boot/initrd.img-* /boot/System.map-* /boot/uInitrd-* /boot/vmlinuz-*
@@ -488,7 +489,7 @@ update_kernel() {
 
 # Update the uboot
 update_uboot() {
-    echo -e "${STEPS} Starting to update u-boot..."
+    echo -e "${STEPS} Start updating u-boot..."
 
     # Copy u-boot.ext and u-boot.emmc
     if [[ "${need_overload}" == "yes" && -n "${UBOOT_OVERLOAD}" && -f "/boot/${UBOOT_OVERLOAD}" ]]; then
@@ -512,7 +513,7 @@ update_uboot() {
 
 # Rescue the kernel
 sos_kernel() {
-    echo -e "${STEPS} Starting kernel rescue..."
+    echo -e "${STEPS} Start rescuing kernel..."
 
     # Check the current system running disk
     root_devname="$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print substr($3, 1, length($3)-2)}')"
@@ -587,14 +588,15 @@ sos_kernel() {
 }
 
 # Display help information
+# prettytable (single_border_style): https://github.com/jazzband/prettytable/blob/main/src/prettytable/prettytable.py#L1358
 help_info() {
     clear
     cat <<EOF
   ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
   │  Example: armbian-update -k 5.15.50 -u dev                                                                          │
-  ├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
+  ├───────────┬──────────────┬──────────────────────────┬───────────────────────────────────────────────────────────────┤
   │  Optional │ Default      │ Value                    │ Description                                                   │
-  ├─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
+  ├───────────┼──────────────┼──────────────────────────┼───────────────────────────────────────────────────────────────┤
   │  -r       │ ophub/kernel │ <owner>/<repo>           │ Set the repository for downloading kernels from github.com    │
   │  -u       │ automate     │ stable/rk3588/flippy/dev │ Set the tags suffix of the kernel used                        │
   │  -k       │ latest       │ kernel-version           │ Set the kernel version                                        │
@@ -602,13 +604,13 @@ help_info() {
   │  -b       │ yes          │ yes/no                   │ Automatically backup the current system kernel                │
   │  -m       │ no           │ yes/no                   │ Use Mainline u-boot                                           │
   │  -s       │ None         │ None                     │ [SOS] Restore eMMC with system kernel from USB                │
-  └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
+  └───────────┴──────────────┴──────────────────────────┴───────────────────────────────────────────────────────────────┘
 EOF
     exit 0
 }
 
 # Check script permission
-[[ "$(id -u)" == "0" ]] || error_msg "Please run this script as root: [ sudo $0 ]"
+[[ "$(id -u)" == "0" ]] || error_msg "Please run the script as root: [ sudo $0 ]"
 echo -e "${STEPS} Welcome to the kernel update tool."
 
 # Update or Rescue kernel
@@ -618,13 +620,14 @@ if [[ "${1}" == "-s" ]]; then
 
     # Kernel rescue succeeded
     sync && sleep 3
-    echo -e "${SUCCESS} The kernel rescue is successful, please unplug the USB and reboot the Armbian."
+    echo -e "${SUCCESS} Kernel rescue succeeded. Please remove the USB and restart the Armbian system."
 elif [[ "${1}" == "-h" ]]; then
     # Display help information
     help_info
 else
     # Start updating the kernel
     check_depends
+    check_network
     init_var "${@}"
     query_version
     download_kernel
@@ -635,6 +638,6 @@ else
 
     # Kernel updated successfully
     sync && sleep 3
-    echo -e "${SUCCESS} Successfully updated, automatic restarting..."
+    echo -e "${SUCCESS} Kernel update succeeded. Armbian system is restarting..."
     reboot
 fi
