Add use actions compile kernel templates

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,11 +1,13 @@
-name: "Rebuild armbian for Amlogic s9xxx tv box"
-author: "ophub"
+name: "Rebuild armbian and kernel for Amlogic s9xxx tv box"
+author: "https://github.com/ophub"
 description: "Support Amlogic s9xxx tv box are s922x, s905x3, s905x2, s912, s905d, s905x, s905w, s905, etc."
 inputs:
-  mode:
-    description: "Choose script."
+  # Choose build target
+  build_target:
+    description: "Choose build target: armbian / kernel"
     required: false
-    default: "ophub"
+    default: "armbian"
+  # For build armbian -----
   armbian_soc:
     description: "Set Amlogic SoC."
     required: false
@@ -30,6 +32,23 @@ inputs:
     description: "Set armbian original file path."
     required: false
     default: "build/output/images/*.img"
+  # For compile kernel -----
+  kernel_repo:
+    description: "select kernel repository"
+    required: false
+    default: "unifreq"
+  kernel_version:
+    description: "select kernel version"
+    required: false
+    default: "5.10.90_5.4.170"
+  kernel_auto:
+    description: "Auto use the latest kernel"
+    required: false
+    default: "true"
+  kernel_sign:
+    description: "Set the kernel custom signature"
+    required: false
+    default: "-meson64-dev"
 
 runs:
   using: "composite"
@@ -37,59 +56,100 @@ runs:
     - shell: bash
       run: |
         cd ${GITHUB_ACTION_PATH}
-        echo -e "Armbian rebuild actions path: ${PWD}"
+        build_target="${{ inputs.build_target }}"
+        [ -z "${build_target}" ] && build_target="armbian"
 
-        armbian_file="${{ inputs.armbian_path }}"
-        armbian_filepath="build/output/images"
-        echo -e "Get armbian file input parameters: [ ${armbian_file} ]"
-        [ -z "${armbian_file}" ] && echo -e "The [ armbian_path ] variable must be specified." && exit 1
-        [ -d "${armbian_filepath}" ] || sudo mkdir -p ${armbian_filepath}
-        if [[ "${armbian_file}" == http* ]]; then
-          echo -e "Use wget to download file: [ ${armbian_file} ]"
-          sudo wget ${armbian_file} -q -P ${armbian_filepath} 2>/dev/null
-        elif [[ "${armbian_file:0:6}" != "build/" && "${armbian_file:0:8}" != "./build/" ]]; then
-          echo -e "Copy files: [ ${armbian_file} ]"
-          sudo cp -f ${GITHUB_WORKSPACE}/${armbian_file} ${armbian_filepath} 2>/dev/null
+        if [ "${build_target}" == "armbian" ]; then
+
+          cd ${GITHUB_ACTION_PATH}
+          echo -e "Rebuild the armbian actions path: ${PWD}"
+
+          armbian_file="${{ inputs.armbian_path }}"
+          armbian_filepath="build/output/images"
+          echo -e "Get armbian file input parameters: [ ${armbian_file} ]"
+          [ -z "${armbian_file}" ] && echo -e "The [ armbian_path ] variable must be specified." && exit 1
+          [ -d "${armbian_filepath}" ] || sudo mkdir -p ${armbian_filepath}
+          if [[ "${armbian_file}" == http* ]]; then
+            echo -e "Use wget to download file: [ ${armbian_file} ]"
+            sudo wget ${armbian_file} -q -P ${armbian_filepath} 2>/dev/null
+          elif [[ "${armbian_file:0:6}" != "build/" && "${armbian_file:0:8}" != "./build/" ]]; then
+            echo -e "Copy files: [ ${armbian_file} ]"
+            sudo cp -f ${GITHUB_WORKSPACE}/${armbian_file} ${armbian_filepath} 2>/dev/null
+          else
+            echo -e "Use armbian files: [ ${armbian_file} ]"
+          fi
+          sync
+          echo -e "About the ${armbian_filepath} directory: \n $(ls ${armbian_filepath} -l 2>/dev/null)"
+
+          cd ${GITHUB_ACTION_PATH}/${armbian_filepath}
+          echo -e "Check the armbian file format..."
+          down_file="$(ls . -l 2>/dev/null | grep "^-" | awk '{print $9}' | head -n 1)"
+          [ -z "${down_file}" ] && echo -e "The [ ${armbian_file} ] is invalid." && exit 1
+          [ "${down_file:0-7}" == ".img.gz" ] && sudo gzip -df ${down_file} 2>/dev/null && sync
+          [ "${down_file:0-7}" == ".img.xz" ] && sudo xz -d ${down_file} 2>/dev/null && sync
+          [ "${down_file:0-4}" == ".zip" ] && sudo unzip -o ${down_file} 2>/dev/null && sync
+          echo -e "Armbian file: [ $(ls *.img -l 2>/dev/null) ]"
+
+          cd ${GITHUB_ACTION_PATH}
+          echo -e "Start to rebuild armbian..."
+          make_command=" -d"
+          [ -n ${{ inputs.armbian_soc }} ] && make_command="${make_command} -b ${{ inputs.armbian_soc }}"
+          [ -n ${{ inputs.armbian_kernel }} ] && make_command="${make_command} -k ${{ inputs.armbian_kernel }}"
+          [ -n ${{ inputs.version_branch }} ] && make_command="${make_command} -v ${{ inputs.version_branch }}"
+          [ -n ${{ inputs.auto_kernel }} ] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
+          [ -n ${{ inputs.armbian_size }} ] && make_command="${make_command} -s ${{ inputs.armbian_size }}"
+          sudo chmod +x rebuild
+          sudo ./rebuild ${make_command}
+
+          cd ${GITHUB_ACTION_PATH}/${armbian_filepath}
+          echo -e "The armbian files in the [ ${armbian_filepath} ] directory. \n"
+          sudo gzip *.img && sync
+
+          cd ${GITHUB_ACTION_PATH}
+          echo -e "Output environment variables."
+          echo "PACKAGED_OUTPUTPATH=${PWD}/${armbian_filepath}" >> $GITHUB_ENV
+          echo "PACKAGED_OUTPUTDATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
+          echo "PACKAGED_STATUS=success" >> $GITHUB_ENV
+          echo -e "PACKAGED_OUTPUTPATH: ${PWD}/${armbian_filepath}"
+          echo -e "PACKAGED_OUTPUTDATE: $(date +"%Y.%m.%d.%H%M")"
+          echo -e "PACKAGED_STATUS: success"
+          echo -e "PACKAGED_OUTPUTPATH files list:"
+          echo -e "$(ls ${PWD}/${armbian_filepath} 2>/dev/null) \n"
+
+        elif [ "${build_target}" == "kernel" ]; then
+
+          cd ${GITHUB_ACTION_PATH}
+          echo -e "Compile the kernel actions path: ${PWD}"
+
+          make_command=" -d"
+          [ -n ${{ inputs.kernel_repo }} ] && make_command="${make_command} -r ${{ inputs.kernel_repo }}"
+          [ -n ${{ inputs.kernel_version }} ] && make_command="${make_command} -k ${{ inputs.kernel_version }}"
+          [ -n ${{ inputs.kernel_auto }} ] && make_command="${make_command} -a ${{ inputs.kernel_auto }}"
+          [ -n ${{ inputs.kernel_sign }} ] && make_command="${make_command} -n ${{ inputs.kernel_sign }}"
+          sudo chmod +x recompile
+          sudo ./recompile ${make_command}
+
+          kernel_filepath="compile-kernel/output"
+          echo -e "The kernel files in the [ ${kernel_filepath} ] directory. \n"
+
+          cd ${GITHUB_ACTION_PATH}
+          output_tags="$(ls ${PWD}/${kernel_filepath}/*.tar.gz -l | awk '{print $9}' | grep -oE '[1-9].[0-9]{1,3}.[0-9]+' | xargs | tr "[ ]" "_")"
+          echo -e "Output environment variables."
+          echo "PACKAGED_OUTPUTTAGS=${output_tags}" >> $GITHUB_ENV
+          echo "PACKAGED_OUTPUTPATH=${PWD}/${kernel_filepath}" >> $GITHUB_ENV
+          echo "PACKAGED_OUTPUTDATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
+          echo "PACKAGED_STATUS=success" >> $GITHUB_ENV
+          echo -e "PACKAGED_OUTPUTTAGS: ${output_tags}"
+          echo -e "PACKAGED_OUTPUTPATH: ${PWD}/${kernel_filepath}"
+          echo -e "PACKAGED_OUTPUTDATE: $(date +"%Y.%m.%d.%H%M")"
+          echo -e "PACKAGED_STATUS: success"
+          echo -e "PACKAGED_OUTPUTPATH files list:"
+          echo -e "$(ls ${PWD}/${kernel_filepath} 2>/dev/null) \n"
+
         else
-          echo -e "Use armbian files: [ ${armbian_file} ]"
+          echo -e "Please select a build target: armbian / kernel"
+          exit 1
         fi
-        sync
-        echo -e "About the ${armbian_filepath} directory: \n $(ls ${armbian_filepath} -l 2>/dev/null)"
-
-        cd ${GITHUB_ACTION_PATH}/${armbian_filepath}
-        echo -e "Check the armbian file format..."
-        down_file="$(ls . -l 2>/dev/null | grep "^-" | awk '{print $9}' | head -n 1)"
-        [ -z "${down_file}" ] && echo -e "The [ ${armbian_file} ] is invalid." && exit 1
-        [ "${down_file:0-7}" == ".img.gz" ] && sudo gzip -df ${down_file} 2>/dev/null && sync
-        [ "${down_file:0-7}" == ".img.xz" ] && sudo xz -d ${down_file} 2>/dev/null && sync
-        [ "${down_file:0-4}" == ".zip" ] && sudo unzip -o ${down_file} 2>/dev/null && sync
-        echo -e "Armbian file: [ $(ls *.img -l 2>/dev/null) ]"
-
-        cd ${GITHUB_ACTION_PATH}
-        echo -e "Start to rebuild armbian..."
-        make_command=" -d"
-        [ -n ${{ inputs.armbian_soc }} ] && make_command="${make_command} -b ${{ inputs.armbian_soc }}"
-        [ -n ${{ inputs.armbian_kernel }} ] && make_command="${make_command} -k ${{ inputs.armbian_kernel }}"
-        [ -n ${{ inputs.version_branch }} ] && make_command="${make_command} -v ${{ inputs.version_branch }}"
-        [ -n ${{ inputs.auto_kernel }} ] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
-        [ -n ${{ inputs.armbian_size }} ] && make_command="${make_command} -s ${{ inputs.armbian_size }}"
-        sudo chmod +x rebuild
-        sudo ./rebuild ${make_command}
-
-        cd ${GITHUB_ACTION_PATH}/${armbian_filepath}
-        echo -e "Compress the .img file in the [ ${armbian_filepath} ] directory. \n"
-        sudo gzip *.img && sync
-
-        cd ${GITHUB_ACTION_PATH}
-        echo -e "Output environment variables."
-        echo "PACKAGED_OUTPUTPATH=${PWD}/${armbian_filepath}" >> $GITHUB_ENV
-        echo "PACKAGED_OUTPUTDATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
-        echo "PACKAGED_STATUS=success" >> $GITHUB_ENV
-        echo -e "PACKAGED_OUTPUTPATH: ${PWD}/${armbian_filepath}"
-        echo -e "PACKAGED_OUTPUTDATE: $(date +"%Y.%m.%d.%H%M")"
-        echo -e "PACKAGED_STATUS: success"
-        echo -e "PACKAGED_OUTPUTPATH files list:"
-        echo -e "$(ls ${PWD}/${armbian_filepath} 2>/dev/null) \n"
 
 branding:
   icon: "terminal"
