Adjust shell syntax

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -70,9 +70,9 @@ runs:
         cd ${GITHUB_ACTION_PATH}
         echo -e "Current running path: [ ${PWD} ]"
         build_target="${{ inputs.build_target }}"
-        [ -z "${build_target}" ] && build_target="armbian"
+        [[ -z "${build_target}" ]] && build_target="armbian"
 
-        if [ "${build_target}" == "armbian" ]; then
+        if [[ "${build_target}" == "armbian" ]]; then
 
             cd ${GITHUB_ACTION_PATH}
             echo -e "Start rebuilding Armbian..."
@@ -80,14 +80,14 @@ runs:
             armbian_file="${{ inputs.armbian_path }}"
             armbian_filepath="build/output/images"
             echo -e "Get armbian file input parameters: [ ${armbian_file} ]"
-            [ -z "${armbian_file}" ] && echo -e "The [ armbian_path ] variable must be specified." && exit 1
-            [ -d "${armbian_filepath}" ] || mkdir -p ${armbian_filepath}
+            [[ -z "${armbian_file}" ]] && echo -e "The [ armbian_path ] variable must be specified." && exit 1
+            [[ -d "${armbian_filepath}" ]] || mkdir -p ${armbian_filepath}
             if [[ "${armbian_file}" == http* ]]; then
                 echo -e "Use wget to download file: [ ${armbian_file} ]"
                 wget ${armbian_file} -q -P ${armbian_filepath} 2>/dev/null
             else
                 echo -e "Copy files: [ ${armbian_file} ]"
-                cp -f ${GITHUB_WORKSPACE}/${armbian_file} ${armbian_filepath} 2>/dev/null
+                cp -vf ${GITHUB_WORKSPACE}/${armbian_file} ${armbian_filepath} 2>/dev/null
             fi
             sync
             echo -e "About the ${armbian_filepath} directory: \n$(ls -l ${armbian_filepath} 2>/dev/null)"
@@ -95,22 +95,22 @@ runs:
             cd ${GITHUB_ACTION_PATH}/${armbian_filepath}
             echo -e "Check the armbian file format..."
             down_file="$(ls -l . 2>/dev/null | grep "^-" | awk '{print $9}' | head -n 1)"
-            [ -z "${down_file}" ] && echo -e "The [ ${armbian_file} ] is invalid." && exit 1
-            [ "${down_file:0-7}" == ".img.gz" ] && gzip -df ${down_file} 2>/dev/null && sync
-            [ "${down_file:0-7}" == ".img.xz" ] && xz -d ${down_file} 2>/dev/null && sync
-            [ "${down_file:0-4}" == ".zip" ] && unzip -o ${down_file} 2>/dev/null && sync
+            [[ -z "${down_file}" ]] && echo -e "The [ ${armbian_file} ] is invalid." && exit 1
+            [[ "${down_file:0-7}" == ".img.gz" ]] && gzip -df ${down_file} 2>/dev/null && sync
+            [[ "${down_file:0-7}" == ".img.xz" ]] && xz -d ${down_file} 2>/dev/null && sync
+            [[ "${down_file:0-4}" == ".zip" ]] && unzip -o ${down_file} 2>/dev/null && sync
             echo -e "Armbian file: \n$(ls -l *.img 2>/dev/null)"
 
             cd ${GITHUB_ACTION_PATH}
             echo -e "Start to rebuild armbian..."
             make_command=" -d"
-            [ -n "${{ inputs.armbian_soc }}" ] && make_command="${make_command} -b ${{ inputs.armbian_soc }}"
-            [ -n "${{ inputs.armbian_kernel }}" ] && make_command="${make_command} -k ${{ inputs.armbian_kernel }}"
-            [ -n "${{ inputs.auto_kernel }}" ] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
-            [ -n "${{ inputs.version_branch }}" ] && make_command="${make_command} -v ${{ inputs.version_branch }}"
-            [ -n "${{ inputs.armbian_size }}" ] && make_command="${make_command} -s ${{ inputs.armbian_size }}"
-            [ -n "${{ inputs.armbian_fstype }}" ] && make_command="${make_command} -t ${{ inputs.armbian_fstype }}"
-            [ -n "${{ inputs.armbian_sign }}" ] && make_command="${make_command} -n ${{ inputs.armbian_sign }}"
+            [[ -n "${{ inputs.armbian_soc }}" ]] && make_command="${make_command} -b ${{ inputs.armbian_soc }}"
+            [[ -n "${{ inputs.armbian_kernel }}" ]] && make_command="${make_command} -k ${{ inputs.armbian_kernel }}"
+            [[ -n "${{ inputs.auto_kernel }}" ]] && make_command="${make_command} -a ${{ inputs.auto_kernel }}"
+            [[ -n "${{ inputs.version_branch }}" ]] && make_command="${make_command} -v ${{ inputs.version_branch }}"
+            [[ -n "${{ inputs.armbian_size }}" ]] && make_command="${make_command} -s ${{ inputs.armbian_size }}"
+            [[ -n "${{ inputs.armbian_fstype }}" ]] && make_command="${make_command} -t ${{ inputs.armbian_fstype }}"
+            [[ -n "${{ inputs.armbian_sign }}" ]] && make_command="${make_command} -n ${{ inputs.armbian_sign }}"
             sudo chmod +x rebuild
             sudo ./rebuild ${make_command}
 
@@ -127,7 +127,7 @@ runs:
             echo -e "PACKAGED_STATUS: success"
             echo -e "PACKAGED_OUTPUTPATH files list: \n$(ls -l ${PWD}/${armbian_filepath} 2>/dev/null)"
 
-        elif [ "${build_target}" == "kernel" ]; then
+        elif [[ "${build_target}" == "kernel" ]]; then
 
             cd ${GITHUB_ACTION_PATH}
             echo -e "Start compile kernel..."
@@ -138,7 +138,7 @@ runs:
                 if [[ "$(ls ${GITHUB_WORKSPACE}/${{ inputs.kernel_config }}/config-* -l 2>/dev/null | grep "^-" | wc -l)" -ne "0" ]]; then
                     echo -e "Use a custom kernel compilation template."
                     rm -f ${config_filepath}/* 2>/dev/null && sync
-                    cp -f ${GITHUB_WORKSPACE}/${{ inputs.kernel_config }}/config-* ${config_filepath}/ 2>/dev/null && sync
+                    cp -vf ${GITHUB_WORKSPACE}/${{ inputs.kernel_config }}/config-* ${config_filepath}/ 2>/dev/null && sync
                     echo -e "List of Kernel Custom Compilation Configuration Templates: \n$(ls -l ${config_filepath})"
                 else
                     echo -e "The custom kernel compilation template path is invalid, continue to use the default template."
@@ -148,10 +148,10 @@ runs:
             fi
 
             make_command=" -d"
-            [ -n "${{ inputs.kernel_version }}" ] && make_command="${make_command} -k ${{ inputs.kernel_version }}"
-            [ -n "${{ inputs.kernel_auto }}" ] && make_command="${make_command} -a ${{ inputs.kernel_auto }}"
-            [ -n "${{ inputs.kernel_sign }}" ] && make_command="${make_command} -n ${{ inputs.kernel_sign }}"
-            [ -n "${{ inputs.kernel_repo }}" ] && make_command="${make_command} -r ${{ inputs.kernel_repo }}"
+            [[ -n "${{ inputs.kernel_version }}" ]] && make_command="${make_command} -k ${{ inputs.kernel_version }}"
+            [[ -n "${{ inputs.kernel_auto }}" ]] && make_command="${make_command} -a ${{ inputs.kernel_auto }}"
+            [[ -n "${{ inputs.kernel_sign }}" ]] && make_command="${make_command} -n ${{ inputs.kernel_sign }}"
+            [[ -n "${{ inputs.kernel_repo }}" ]] && make_command="${make_command} -r ${{ inputs.kernel_repo }}"
             sudo chmod +x recompile
             sudo ./recompile ${make_command}
 
