Unified grammar format

diff --git a/recompile b/recompile
--- a/recompile
+++ b/recompile
@@ -76,22 +76,16 @@ qemu_binary_arm="qemu-arm-static"
 qemu_binary_arm64="qemu-aarch64-static"
 #
 # Set font color
-blue_font_prefix="\033[94m"
-purple_font_prefix="\033[95m"
-green_font_prefix="\033[92m"
-yellow_font_prefix="\033[93m"
-red_font_prefix="\033[91m"
-font_color_suffix="\033[0m"
-INFO="[${blue_font_prefix}INFO${font_color_suffix}]"
-STEPS="[${purple_font_prefix}STEPS${font_color_suffix}]"
-SUCCESS="[${green_font_prefix}SUCCESS${font_color_suffix}]"
-WARNING="[${yellow_font_prefix}WARNING${font_color_suffix}]"
-ERROR="[${red_font_prefix}ERROR${font_color_suffix}]"
+STEPS="[\033[95m STEPS \033[0m]"
+INFO="[\033[94m INFO \033[0m]"
+SUCCESS="[\033[92m SUCCESS \033[0m]"
+WARNING="[\033[93m WARNING \033[0m]"
+ERROR="[\033[91m ERROR \033[0m]"
 #
 #==============================================================================================
 
 error_msg() {
-    echo -e " ${ERROR} ${1}"
+    echo -e "${ERROR} ${1}"
     exit 1
 }
 
@@ -99,9 +93,9 @@ init_var() {
     cd ${make_path}
 
     # If it is followed by [ : ], it means that the option requires a parameter value
-    get_all_ver=$(getopt "dk:a:n:r:" "${@}")
+    get_all_ver="$(getopt "dk:a:n:r:" "${@}")"
 
-    while [ -n "${1}" ]; do
+    while [[ -n "${1}" ]]; do
         case "${1}" in
         -d | --Default)
             : ${build_kernel:="${build_kernel}"}
@@ -110,7 +104,7 @@ init_var() {
             : ${repo_owner:="${repo_owner}"}
             ;;
         -k | --Kernel)
-            if [ -n "${2}" ]; then
+            if [[ -n "${2}" ]]; then
                 oldIFS=$IFS
                 IFS=_
                 build_kernel=(${2})
@@ -121,7 +115,7 @@ init_var() {
             fi
             ;;
         -a | --AutoKernel)
-            if [ -n "${2}" ]; then
+            if [[ -n "${2}" ]]; then
                 auto_kernel="${2}"
                 shift
             else
@@ -129,7 +123,7 @@ init_var() {
             fi
             ;;
         -n | --customName)
-            if [ -n "${2}" ]; then
+            if [[ -n "${2}" ]]; then
                 custom_name="${2}"
                 shift
             else
@@ -137,7 +131,7 @@ init_var() {
             fi
             ;;
         -r | --Repository)
-            if [ -n "${2}" ]; then
+            if [[ -n "${2}" ]]; then
                 repo_owner="${2}"
                 shift
             else
@@ -157,8 +151,8 @@ init_var() {
     code_repo="$(echo "${input_r_value}" | awk -F '@' '{print $1}' | awk -F '/' '{print $2}')"
     code_branch="$(echo "${input_r_value}" | awk -F '@' '{print $2}')"
     #
-    [ -n "${code_owner}" ] || error_msg "The [ -r ] parameter is invalid."
-    [ -n "${code_branch}" ] || code_branch="${repo_branch}"
+    [[ -n "${code_owner}" ]] || error_msg "The [ -r ] parameter is invalid."
+    [[ -n "${code_branch}" ]] || code_branch="${repo_branch}"
 }
 
 toolchain_check() {
@@ -174,7 +168,7 @@ toolchain_check() {
         sudo apt-get -qq update
         sudo apt-get -qq install -y $(cat compile-kernel/tools/script/ubuntu2004-build-armbian-depends)
 
-        [ -d "${toolchain_path}" ] || mkdir -p ${toolchain_path}
+        [[ -d "${toolchain_path}" ]] || mkdir -p ${toolchain_path}
 
         # Download gcc for Ubuntu focal
         if [[ ! -d "${toolchain_path}/${gcc_file//.tar.xz/}/bin" ]]; then
@@ -182,7 +176,7 @@ toolchain_check() {
             wget -c "${dev_repo}/${gcc_file}" -O "${toolchain_path}/${gcc_file}" >/dev/null 2>&1 && sync
             tar -xJf ${toolchain_path}/${gcc_file} -C ${toolchain_path} && sync
             rm -f ${toolchain_path}/${gcc_file} && sync
-            [ -d "${toolchain_path}/${gcc_file//.tar.xz/}/bin" ] || error_msg "The gcc is not set!"
+            [[ -d "${toolchain_path}/${gcc_file//.tar.xz/}/bin" ]] || error_msg "The gcc is not set!"
         fi
 
         # Download clang for Ubuntu focal
@@ -191,19 +185,19 @@ toolchain_check() {
             wget -c "${dev_repo}/${clang_file}" -O "${toolchain_path}/${clang_file}" >/dev/null 2>&1 && sync
             tar -xJf ${toolchain_path}/${clang_file} -C ${toolchain_path} && sync
             rm -f ${toolchain_path}/${clang_file} && sync
-            [ -d "${toolchain_path}/${clang_file//.tar.xz/}/bin" ] || error_msg "The clang is not set!"
+            [[ -d "${toolchain_path}/${clang_file//.tar.xz/}/bin" ]] || error_msg "The clang is not set!"
         fi
     fi
 
     # Download armbian
-    if [ ! -f "${armbian_file}" ]; then
+    if [[ ! -f "${armbian_file}" ]]; then
         echo -e "${INFO} Download armbian [ ${armbian_rootfs_file} ] ..."
         rm -rf ${armbian_path} 2>/dev/null && mkdir -p ${armbian_path}
         wget -c "${dev_repo}/${armbian_rootfs_file}" -O "${armbian_path}/${armbian_rootfs_file}" >/dev/null 2>&1 && sync
         tar -xJf ${armbian_path}/${armbian_rootfs_file} -C ${armbian_path} && sync
         mv -f ${armbian_path}/*.img ${armbian_file} && sync
         rm -f ${armbian_path}/${armbian_rootfs_file} && sync
-        [ -f "${armbian_file}" ] || error_msg "There is no armbian file: [ ${armbian_file} ]"
+        [[ -f "${armbian_file}" ]] || error_msg "There is no armbian file: [ ${armbian_file} ]"
     fi
 }
 
@@ -216,27 +210,25 @@ query_version() {
     i=1
     for KERNEL_VAR in ${build_kernel[*]}; do
         echo -e "${INFO} (${i}) Auto query the latest kernel version of the same series for [ ${KERNEL_VAR} ]"
-        MAIN_LINE_M=$(echo "${KERNEL_VAR}" | cut -d '.' -f1)
-        MAIN_LINE_V=$(echo "${KERNEL_VAR}" | cut -d '.' -f2)
-        MAIN_LINE_S=$(echo "${KERNEL_VAR}" | cut -d '.' -f3)
-        MAIN_LINE="${MAIN_LINE_M}.${MAIN_LINE_V}"
+        # Identify the kernel mainline
+        MAIN_LINE="$(echo ${KERNEL_VAR} | awk -F '.' '{print $1"."$2}')"
 
-        if [ "${code_owner}" == "kernel.org" ]; then
+        if [[ "${code_owner}" == "kernel.org" ]]; then
             # latest_version="5.10.100"
-            latest_version=$(curl -s ${kernel_org_repo} | grep -oE linux-${MAIN_LINE}.[0-9]+.tar.xz | sort -rV | head -n 1 | grep -oE '[1-9].[0-9]{1,3}.[0-9]+')
-            if [[ "$?" -eq "0" && ! -z "${latest_version}" ]]; then
+            latest_version="$(curl -s ${kernel_org_repo} | grep -oE linux-${MAIN_LINE}.[0-9]+.tar.xz | sort -rV | head -n 1 | grep -oE '[1-9].[0-9]{1,3}.[0-9]+')"
+            if [[ "${?}" -eq "0" && -n "${latest_version}" ]]; then
                 tmp_arr_kernels[${i}]="${latest_version}"
             else
                 error_msg "Failed to query the kernel version in [ ${kernel_org_repo} ]"
             fi
             echo -e "${INFO} (${i}) [ ${tmp_arr_kernels[$i]} ] is kernel.org latest kernel. \n"
         else
-            if [ -z "${code_repo}" ]; then linux_repo="linux-${MAIN_LINE}.y"; else linux_repo="${code_repo}"; fi
+            if [[ -z "${code_repo}" ]]; then linux_repo="linux-${MAIN_LINE}.y"; else linux_repo="${code_repo}"; fi
             github_kernel_repo="${code_owner}/${linux_repo}/${code_branch}"
             github_kernel_ver="https://raw.githubusercontent.com/${github_kernel_repo}/Makefile"
             # latest_version="180"
             latest_version="$(curl -s ${github_kernel_ver} | grep -oE "SUBLEVEL =.*" | head -n 1 | grep -oE '[0-9]{1,3}')"
-            if [[ "$?" -eq "0" && ! -z "${latest_version}" ]]; then
+            if [[ "${?}" -eq "0" && -n "${latest_version}" ]]; then
                 tmp_arr_kernels[${i}]="${MAIN_LINE}.${latest_version}"
             else
                 error_msg "Failed to query the kernel version in [ github.com/${github_kernel_repo} ]"
@@ -249,29 +241,29 @@ query_version() {
 
     # Reset the kernel array to the latest kernel version
     unset build_kernel
-    build_kernel=${tmp_arr_kernels[*]}
+    build_kernel="${tmp_arr_kernels[*]}"
 }
 
 get_kernel_source() {
     cd ${make_path}
     # kernel_folder > kernel_.tar.xz_file > download_from_kernel.org
     echo -e "${STEPS} Start query and download the kernel."
-    [ -d "${kernel_path}" ] || mkdir -p ${kernel_path}
-    if [ ! -d "${kernel_path}/${local_kernel_path}" ]; then
-        if [ "${code_owner}" == "kernel.org" ]; then
-            if [ -f "${kernel_path}/${local_kernel_path}.tar.xz" ]; then
+    [[ -d "${kernel_path}" ]] || mkdir -p ${kernel_path}
+    if [[ ! -d "${kernel_path}/${local_kernel_path}" ]]; then
+        if [[ "${code_owner}" == "kernel.org" ]]; then
+            if [[ -f "${kernel_path}/${local_kernel_path}.tar.xz" ]]; then
                 echo -e "${INFO} Unzip local files [ ${local_kernel_path}.tar.xz ]"
                 cd ${kernel_path}
                 tar -xJf ${local_kernel_path}.tar.xz
-                [ "$?" -eq "0" ] || error_msg "[ ${local_kernel_path}.tar.xz ] file decompression failed."
+                [[ "${?}" -eq "0" ]] || error_msg "[ ${local_kernel_path}.tar.xz ] file decompression failed."
             else
                 echo -e "${INFO} [ ${kernel_version} ] Kernel loading from [ ${server_kernel_repo}${local_kernel_path}.tar.xz ]"
                 wget -q -P ${kernel_path} ${server_kernel_repo}${local_kernel_path}.tar.xz && sync
-                if [[ "$?" -eq "0" && -s "${kernel_path}/${local_kernel_path}.tar.xz" ]]; then
+                if [[ "${?}" -eq "0" && -s "${kernel_path}/${local_kernel_path}.tar.xz" ]]; then
                     echo -e "${SUCCESS} The kernel file is downloaded successfully."
                     cd ${kernel_path}
                     tar -xJf ${local_kernel_path}.tar.xz && sync
-                    [ -d "${local_kernel_path}" ] || error_msg "[ ${local_kernel_path}.tar.xz ] file decompression failed."
+                    [[ -d "${local_kernel_path}" ]] || error_msg "[ ${local_kernel_path}.tar.xz ] file decompression failed."
                 else
                     error_msg "Kernel file download failed!"
                 fi
@@ -279,7 +271,7 @@ get_kernel_source() {
         else
             echo -e "${INFO} Start cloning from [ https://github.com/${server_kernel_repo} -b ${code_branch} ]"
             git clone --depth 1 https://github.com/${server_kernel_repo} -b ${code_branch} ${kernel_path}/${local_kernel_path}
-            [ "$?" -eq "0" ] || error_msg "[ https://github.com/${server_kernel_repo} ] Clone failed."
+            [[ "${?}" -eq "0" ]] || error_msg "[ https://github.com/${server_kernel_repo} ] Clone failed."
         fi
     elif [ "${code_owner}" != "kernel.org" ]; then
         # Get a local kernel version
@@ -327,17 +319,17 @@ compile_kernel() {
     export ARCH="arm64"
     export LOCALVERSION="${custom_name}"
     if [[ "${host_release}" == "jammy" ]]; then
-        export CROSS_COMPILE=aarch64-linux-gnu-
-        export CC=clang
-        export LD=ld.lld
+        export CROSS_COMPILE="aarch64-linux-gnu-"
+        export CC="clang"
+        export LD="ld.lld"
     else
-        export CROSS_COMPILE=${toolchain_path}/${gcc_file//.tar.xz/}/bin/aarch64-none-linux-gnu-
-        export CC=${toolchain_path}/${clang_file//.tar.xz/}/bin/clang
-        export LD=${toolchain_path}/${clang_file//.tar.xz/}/bin/ld.lld
+        export CROSS_COMPILE="${toolchain_path}/${gcc_file//.tar.xz/}/bin/aarch64-none-linux-gnu-"
+        export CC="${toolchain_path}/${clang_file//.tar.xz/}/bin/clang"
+        export LD="${toolchain_path}/${clang_file//.tar.xz/}/bin/ld.lld"
         #
         # Add $PATH variable
         path_ubuntu="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
-        path_clang=${toolchain_path}/${clang_file//.tar.xz/}/bin:${path_ubuntu}
+        path_clang="${toolchain_path}/${clang_file//.tar.xz/}/bin:${path_ubuntu}"
         # Set $PATH variable for ~/.bashrc
         sed -i '/^PATH=/d' ~/.bashrc 2>/dev/null && sync
         echo "PATH=${path_clang}" >>~/.bashrc && sync
@@ -364,12 +356,12 @@ compile_kernel() {
     #make ${MAKE_SET_STRING} menuconfig
 
     # Check .config file
-    if [ ! -f ".config" ]; then
+    if [[ ! -s ".config" ]]; then
         # Copy config file
         echo -e "${INFO} Copy config file to ${local_kernel_path}"
-        config_demo=$(ls ${config_path}/config-${kernel_verpatch}* 2>/dev/null | sort -rV | head -n 1)
-        config_demo_file=${config_demo##*/}
-        [ -z "${config_demo_file}" ] && error_msg "Missing [ config-${kernel_verpatch}* ] template!"
+        config_demo="$(ls ${config_path}/config-${kernel_verpatch}* 2>/dev/null | sort -rV | head -n 1)"
+        config_demo_file="${config_demo##*/}"
+        [[ -z "${config_demo_file}" ]] && error_msg "Missing [ config-${kernel_verpatch}* ] template!"
         echo -e "${INFO} CONFIG_DEMO: [ ${config_path}/${config_demo_file} ]"
         cp -f ${config_path}/${config_demo_file} .config && sync
     else
@@ -380,8 +372,8 @@ compile_kernel() {
     sync
 
     # Enable/Disabled Linux Kernel Clang LTO
-    kernel_x=$(echo "${kernel_version}" | cut -d '.' -f1)
-    kernel_y=$(echo "${kernel_version}" | cut -d '.' -f2)
+    kernel_x="$(echo "${kernel_version}" | cut -d '.' -f1)"
+    kernel_y="$(echo "${kernel_version}" | cut -d '.' -f2)"
     if [[ "${kernel_x}" -ge "6" ]] || [[ "${kernel_x}" -eq "5" && "${kernel_y}" -ge "12" ]]; then
         scripts/config -e LTO_CLANG_THIN
     else
@@ -391,19 +383,19 @@ compile_kernel() {
     # Make kernel
     echo -e "${STEPS} Start compilation kernel [ ${local_kernel_path} ]..."
     PROCESS="$(cat /proc/cpuinfo | grep "processor" | wc -l)"
-    [ -z ${PROCESS} ] && PROCESS="1" && echo "PROCESS: 1"
+    [[ -z "${PROCESS}" ]] && PROCESS="1" && echo "PROCESS: 1"
     make ${MAKE_SET_STRING} Image modules dtbs -j${PROCESS}
-    [ $? -eq 0 ] && echo -e "${SUCCESS} The kernel is compiled successfully."
+    [[ "${?}" -eq "0" ]] && echo -e "${SUCCESS} The kernel is compiled successfully."
 
     # Install modules
     echo -e "${STEPS} Install modules ..."
     make ${MAKE_SET_STRING} INSTALL_MOD_PATH=${out_kernel}/modules modules_install
-    [ $? -eq 0 ] && echo -e "${SUCCESS} The modules is installed successfully."
+    [[ "${?}" -eq "0" ]] && echo -e "${SUCCESS} The modules is installed successfully."
 
     # Install headers
     echo -e "${STEPS} Install headers ..."
     make ${MAKE_SET_STRING} INSTALL_HDR_PATH=${out_kernel}/header headers_install
-    [ $? -eq 0 ] && echo -e "${SUCCESS} The headers is installed successfully."
+    [[ "${?}" -eq "0" ]] && echo -e "${SUCCESS} The headers is installed successfully."
 }
 
 generate_uinitrd() {
@@ -413,10 +405,10 @@ generate_uinitrd() {
     cp -f ${armbian_file} ${chroot_file} && sync
 
     # Mount the armbian system
-    tag_rootfs=${chroot_path}/root
+    tag_rootfs="${chroot_path}/root"
 
-    loop_armbian=$(losetup -P -f --show "${chroot_file}")
-    [ ${loop_armbian} ] || error_msg "losetup ${chroot_file} failed."
+    loop_armbian="$(losetup -P -f --show "${chroot_file}")"
+    [[ -n "${loop_armbian}" ]] || error_msg "losetup ${chroot_file} failed."
 
     if ! mount ${loop_armbian}p2 ${tag_rootfs}; then
         error_msg "mount ${loop_armbian}p2 failed!"
@@ -443,8 +435,8 @@ generate_uinitrd() {
     sed -i "/^COMPRESS=/d" ${compress_initrd_file} && sync
     echo "COMPRESS=gzip" >>${compress_initrd_file} && sync
 
-    [ -f "/usr/bin/${qemu_binary_arm}" ] && cp -f /usr/bin/${qemu_binary_arm} ${tag_rootfs}/usr/bin/ && sync
-    [ -f "/usr/bin/${qemu_binary_arm64}" ] && cp -f /usr/bin/${qemu_binary_arm64} ${tag_rootfs}/usr/bin/ && sync
+    [[ -f "/usr/bin/${qemu_binary_arm}" ]] && cp -f /usr/bin/${qemu_binary_arm} ${tag_rootfs}/usr/bin/ && sync
+    [[ -f "/usr/bin/${qemu_binary_arm64}" ]] && cp -f /usr/bin/${qemu_binary_arm64} ${tag_rootfs}/usr/bin/ && sync
     #echo -e "${INFO} The [ ${qemu_binary_arm64} ] file copy results: \n$(ls -l ${tag_rootfs}/usr/bin/${qemu_binary_arm64}) \n"
 
     cp -f ${script_path}/ubuntu_chroot_armbian.sh ${tag_rootfs}/root 2>/dev/null && sync
@@ -454,7 +446,7 @@ generate_uinitrd() {
     # Enter the armbian system to generate /boot/uInitrd-${kernel_outname} file
     echo -e "${INFO} Enter the chroot armbian system..."
     chroot ${tag_rootfs} /bin/bash -c "/root/ubuntu_chroot_armbian.sh ${kernel_outname}"
-    [[ $? -ne 0 || ! -f "${tag_rootfs}"/boot/uInitrd-${kernel_outname} ]] && error_msg "Create chroot uInitrd-${kernel_outname} file failed."
+    [[ "${?}" -ne "0" || ! -f "${tag_rootfs}"/boot/uInitrd-${kernel_outname} ]] && error_msg "Create chroot uInitrd-${kernel_outname} file failed."
 
     cd ${make_path}
     # Copy the generated uInitrd file to the current system
@@ -531,7 +523,7 @@ clean_tmp() {
 loop_recompile() {
     cd ${make_path}
 
-    j=1
+    j="1"
     for k in ${build_kernel[*]}; do
         # kernel_version, such as [ 5.10.100 ]
         kernel_version="${k}"
@@ -541,10 +533,10 @@ loop_recompile() {
         kernel_sub="$(echo ${kernel_version} | awk -F '.' '{print $3}')"
 
         # The loop variable assignment
-        if [ "${code_owner}" == "kernel.org" ]; then
+        if [[ "${code_owner}" == "kernel.org" ]]; then
             server_kernel_repo="${kernel_org_repo}"
             local_kernel_path="linux-${kernel_version}"
-        elif [ -z "${code_repo}" ]; then
+        elif [[ -z "${code_repo}" ]]; then
             server_kernel_repo="${code_owner}/linux-${kernel_verpatch}.y"
             local_kernel_path="linux-${kernel_verpatch}.y"
         else
@@ -565,7 +557,7 @@ loop_recompile() {
 }
 
 # Check script permission, supports running on x86_64 Ubuntu: [ jammy / focal ]
-[[ "$(id -u)" == "0" ]] || error_msg "Please run this script as root: [ sudo ./$0 ]"
+[[ "$(id -u)" == "0" ]] || error_msg "Please run this script as root: [ sudo ./${0} ]"
 [[ -n "${host_release}" && "jammy focal" == *"${host_release}"* ]] || error_msg "Supports running on Ubuntu: [ jammy / focal ]"
 [[ "${arch_info}" == "x86_64" ]] || error_msg "Running this tool on non-x86_64 Ubuntu build hosts is not supported."
 # Show welcome and server start information
