Update install script

diff --git a/amlogic-s9xxx/common-files/files/usr/bin/armbian-install b/amlogic-s9xxx/common-files/files/usr/bin/armbian-install
--- a/amlogic-s9xxx/common-files/files/usr/bin/armbian-install
+++ b/amlogic-s9xxx/common-files/files/usr/bin/armbian-install
@@ -7,7 +7,7 @@
 
 cat <<EOF
 **************************************************************************
-Please select Amlogic s9xxx box, Determine the skipped space (unit: MB):
+Please select amlogic s9xxx box model:
 
 1.  X96-Max+ (4G DDR) -------- [ S905x3 / CPU: 2124Mtz / NETWORK: 1000M ]
 2.  HK1-Box (4G DDR) --------- [ S905x3 / CPU: 2124Mtz / NETWORK: 1000M ]
@@ -32,33 +32,125 @@ BOOT=256
 
 read select
 case "${select}" in
-    1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9)
-        SKIP=1350
-        ;;
-    10 | 11 | 12 | 13)
-        SKIP=700
-        ;;
-    0)
-        echo -ne "Please enter the size (MB) to be skipped, it can only be (68-2048) :"
-        read skip
-            if [ -z "${skip}" ];then
-                echo "Input error."
-                exit 1
-            fi
-            if (( ${skip} >= 68  && ${skip} <= 2048 ));then
-                SKIP=${skip}
-            else
-                echo "Input error: ${skip}"
-                exit 1
-            fi
-        ;;
-    *)
-        echo "Invalid input."
-        exit 1
-        ;;
+      1) FDTFILE="meson-sm1-x96-max-plus.dtb"
+         UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
+         MAINLINE_UBOOT="/lib/u-boot/x96maxplus-u-boot.bin.sd.bin"
+         ANDROID_UBOOT="/lib/u-boot/hk1box-bootloader.img"
+         AMLOGIC_SOC="s905x3"
+         SKIP=1350
+         ;;
+      2) FDTFILE="meson-sm1-hk1box-vontar-x3.dtb"
+         UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
+         MAINLINE_UBOOT="/lib/u-boot/hk1box-u-boot.bin.sd.bin"
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s905x3"
+         SKIP=1350
+         ;;
+      3) FDTFILE="meson-sm1-h96-max-x3.dtb"
+         UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
+         MAINLINE_UBOOT="/lib/u-boot/h96maxx3-u-boot.bin.sd.bin"
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s905x3"
+         SKIP=1350
+         ;;
+      4) FDTFILE="meson-sm1-ugoos-x3.dtb"
+         UBOOT_OVERLOAD="u-boot-ugoos-x3.bin"
+         MAINLINE_UBOOT=""
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s905x3"
+         SKIP=1350
+         ;;
+      5) FDTFILE="meson-g12a-x96-max.dtb"
+         UBOOT_OVERLOAD="u-boot-x96max.bin"
+         MAINLINE_UBOOT="/lib/u-boot/x96max-u-boot.bin.sd.bin"
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s905x2"
+         SKIP=1350
+         ;;
+      6) FDTFILE="meson-g12a-x96-max-rmii.dtb"
+         UBOOT_OVERLOAD="u-boot-x96max.bin"
+         MAINLINE_UBOOT="/lib/u-boot/x96max-u-boot.bin.sd.bin"
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s905x2"
+         SKIP=1350
+         ;;
+      7) FDTFILE="meson-g12b-gtking.dtb"
+         UBOOT_OVERLOAD="u-boot-gtkingpro.bin"
+         MAINLINE_UBOOT="/lib/u-boot/gtking-u-boot.bin.sd.bin"
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s922x"
+         SKIP=1350
+         ;;
+      8) FDTFILE="meson-g12b-gtking-pro.dtb"
+         UBOOT_OVERLOAD="u-boot-gtkingpro.bin"
+         MAINLINE_UBOOT="/lib/u-boot/gtkingpro-u-boot.bin.sd.bin"
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s922x"
+         SKIP=1350
+         ;;
+      9) FDTFILE="meson-g12b-ugoos-am6.dtb"
+         UBOOT_OVERLOAD="u-boot-gtkingpro.bin"
+         MAINLINE_UBOOT="/lib/u-boot/gtkingpro-u-boot.bin.sd.bin"
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s922x"
+         SKIP=1350
+         ;;
+      10) FDTFILE="meson-gxm-octopus-planet.dtb"
+         UBOOT_OVERLOAD="u-boot-zyxq.bin"
+         MAINLINE_UBOOT=""
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s912"
+         SKIP=700
+         ;;
+      11) FDTFILE="meson-gxl-s905d-phicomm-n1.dtb"
+         UBOOT_OVERLOAD="u-boot-n1.bin"
+         MAINLINE_UBOOT=""
+         ANDROID_UBOOT="/lib/u-boot/u-boot-2015-phicomm-n1.bin"
+         AMLOGIC_SOC="s905d"
+         SKIP=700
+         ;;
+      12) FDTFILE="meson-gxl-s905x-p212.dtb"
+         UBOOT_OVERLOAD="u-boot-p212.bin"
+         MAINLINE_UBOOT=""
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s905x"
+         SKIP=700
+         ;;
+      13) FDTFILE="meson-gxl-s905w-tx3-mini.dtb"
+         UBOOT_OVERLOAD="u-boot-s905x-s912.bin"
+         MAINLINE_UBOOT=""
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC="s905w"
+         SKIP=700
+         ;;
+      99) FDTFILE=${SPECIFY_DTB}
+         UBOOT_OVERLOAD=""
+         MAINLINE_UBOOT=""
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC=""
+         SKIP=700
+         ;;
+      0) cat <<EOF
+Please enter the .dtb file name of your box, do not include the path.
+For example: $FDTFILE
+EOF
+         echo  "Enter the .dtb File name:"
+         read  CUST_FDTFILE
+         FDTFILE=${CUST_FDTFILE}
+         UBOOT_OVERLOAD=""
+         MAINLINE_UBOOT=""
+         ANDROID_UBOOT=""
+         AMLOGIC_SOC=""
+         SKIP=700
+         ;;
+      *) echo "Input error, exit!"
+         exit 1
+         ;;
 esac
 
+echo -e "FDT Value [ ${FDTFILE} ]"
 echo "SKIP = ${SKIP} MB"
+
 systemctl stop armbian-resize-filesystem.service
 systemctl disable armbian-resize-filesystem.service
 
@@ -140,13 +232,22 @@ parted -s "${DEV_EMMC}" mklabel msdos 2>/dev/null
 parted -s "${DEV_EMMC}" mkpart primary fat32 $((SKIP*1024*1024))b $(( (SKIP+BOOT)*1024*1024 - 1 ))b 2>/dev/null
 parted -s "${DEV_EMMC}" mkpart primary ext4 $(( (SKIP+BOOT)*1024*1024 ))b 100% 2>/dev/null
 
-echo "Start restore u-boot"
-dd if=/root/u-boot-default-aml.img of="${DEV_EMMC}" conv=fsync bs=1 count=442 
-dd if=/root/u-boot-default-aml.img of="${DEV_EMMC}" conv=fsync bs=512 skip=1 seek=1
-sync
+echo "Start write u-boot"
+if  [[ -n "${MAINLINE_UBOOT}" && -f ${MAINLINE_UBOOT} ]]; then
+    echo -e "Write Mainline bootloader: [ ${MAINLINE_UBOOT} ]"
+    dd if=${MAINLINE_UBOOT} of=${DEV_EMMC} bs=1 count=444 conv=fsync
+    dd if=${MAINLINE_UBOOT} of=${DEV_EMMC} bs=512 skip=1 seek=1 conv=fsync
+elif [[ -n "${ANDROID_UBOOT}" && -f "${ANDROID_UBOOT}" ]]; then
+    echo -e "Write Android bootloader: [ ${ANDROID_UBOOT} ]"
+    dd if=${ANDROID_UBOOT} of=${DEV_EMMC} bs=1 count=444 conv=fsync
+    dd if=${ANDROID_UBOOT} of=${DEV_EMMC} bs=512 skip=1 seek=1 conv=fsync
+else
+    echo "Restore the original u-boot"
+    dd if=/root/u-boot-default-aml.img of="${DEV_EMMC}" conv=fsync bs=1 count=442
+    dd if=/root/u-boot-default-aml.img of="${DEV_EMMC}" conv=fsync bs=512 skip=1 seek=1
+fi
 
 echo "Start copy system for eMMC."
-
 mkdir -p /ddbr
 chmod 777 /ddbr
 
@@ -168,36 +269,27 @@ mkfs.vfat -n "BOOT_EMMC" ${PART_BOOT}
 
 mount -o rw ${PART_BOOT} ${DIR_INSTALL}
 
-echo "Copying BOOT..."
+echo "Start copy BOOT_EMMC partition data..."
 cp -rf /boot/* ${DIR_INSTALL} && sync
 rm -rf ${DIR_INSTALL}/'System Volume Information' 2>/dev/null
 
 echo "Edit init config..."
-lines=$(wc -l < ${DIR_INSTALL}/uEnv.txt)
-let lines=lines-1
-head -n $lines ${DIR_INSTALL}/uEnv.txt > ${DIR_INSTALL}/uEnv-emmc.txt
+sed -i "s|ROOTFS|ROOTFS_EMMC|g" ${DIR_INSTALL}/uEnv.txt
+sed -i "s|meson.*.dtb|${FDTFILE}|g" ${DIR_INSTALL}/uEnv.txt
 
-cat >> ${DIR_INSTALL}/uEnv-emmc.txt <<EOF
-APPEND=root=LABEL=ROOTFS_EMMC rootflags=data=writeback rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
-EOF
-
-mv -f ${DIR_INSTALL}/uEnv-emmc.txt ${DIR_INSTALL}/uEnv.txt
-touch ${DIR_INSTALL}/uEnv.txt
-cp -f ${DIR_INSTALL}/uEnv.txt /root/uEnv.emmc
-if [ "${K510}" -eq "1" ];then
-    cp -f ${DIR_INSTALL}/uEnv.txt /boot/uEnv.emmc
-fi
-cp -f /boot/uEnv.txt  /root/uEnv.sd
 rm ${DIR_INSTALL}/s9*
 rm ${DIR_INSTALL}/aml*
 mv -f ${DIR_INSTALL}/boot-emmc.ini ${DIR_INSTALL}/boot.ini
-sed -e "s/u-boot.ext/u-boot.emmc/g" -i "${DIR_INSTALL}/boot.ini"
+sed -i "s|u-boot.ext|u-boot.emmc|g" ${DIR_INSTALL}/boot.ini
 mv -f ${DIR_INSTALL}/boot-emmc.scr ${DIR_INSTALL}/boot.scr
 mv -f ${DIR_INSTALL}/boot-emmc.cmd ${DIR_INSTALL}/boot.cmd
-if [ -f /boot/u-boot.ext ] ; then
-    if [ "${K510}" -eq "1" ];then
-        cp -f ${DIR_INSTALL}/u-boot.ext ${DIR_INSTALL}/u-boot.emmc
+
+if [ "${K510}" -eq "1" ]; then
+    if [ -f ${DIR_INSTALL}/${UBOOT_OVERLOAD} ]; then
+        echo "Copy [ ${UBOOT_OVERLOAD} ] to u-boot.emmc"
+        cp -f ${DIR_INSTALL}/${UBOOT_OVERLOAD} ${DIR_INSTALL}/u-boot.emmc
     else
+        echo "Mv [ u-boot.sd ] to u-boot.emmc"
         mv -f ${DIR_INSTALL}/u-boot.sd ${DIR_INSTALL}/u-boot.emmc
     fi
 fi
@@ -213,7 +305,7 @@ fi
 echo "Formatting ROOT partition..."
 mkfs.ext4 -F -L ROOTFS_EMMC ${PART_ROOT}
 
-echo "Copying ROOTFS."
+echo "Start copy ROOTFS_EMMC partition data..."
 mount -t ext4 ${PART_ROOT} ${DIR_INSTALL}
 
 cd /
@@ -226,23 +318,20 @@ for src in ${COPY_SRC}; do
 done
 echo "Copy complete."
 
-echo "Copy fstab"
 rm ${DIR_INSTALL}/etc/fstab
 cat > ${DIR_INSTALL}/etc/fstab<<EOF
 /dev/root       /               ext4            defaults,noatime,errors=remount-ro     	0 1
-EOF
-
-cat >> ${DIR_INSTALL}/etc/fstab <<EOF
 LABEL=BOOT_EMMC /boot           vfat            defaults                                0 0
 tmpfs           /tmp            tmpfs           defaults,nosuid                         0 0
 EOF
 
-rm -f ${DIR_INSTALL}/root/fstab
 cd /
 sync
 umount ${DIR_INSTALL}
+sleep 3
 
 echo "*************************************************************************************************"
 echo "Successful installed, please unplug the USB, re-insert the power supply to start the armbian."
 echo "*************************************************************************************************"
+exit 0
 
