Add partition creation script when using TF/USB

diff --git a/amlogic-s9xxx/common-files/files/usr/sbin/armbian-update b/amlogic-s9xxx/common-files/files/usr/sbin/armbian-update
--- a/amlogic-s9xxx/common-files/files/usr/sbin/armbian-update
+++ b/amlogic-s9xxx/common-files/files/usr/sbin/armbian-update
@@ -3,7 +3,7 @@
 # Copyright (C) 2020- https://github.com/unifreq/openwrt_packit
 # Copyright (C) 2021- https://github.com/ophub/amlogic-s9xxx-armbian
 #
-# Description: Armbian kernel update (For Amlogic box)
+# Description: Armbian kernel update
 # Kernel download: https://github.com/ophub/flippy-kernel/tree/main/library
 #
 # When the kernel version is upgraded from 5.10 or lower to 5.10 or higher, need to install U-BOOT.
@@ -30,8 +30,22 @@ die() {
 }
 
 echo -e "Start update the armbian kernel."
-# Operation environment check
-EMMC_NAME="$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9]?boot0)' | sed "s/boot0//g")"
+
+# Find the partition where root is located
+ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
+if [ "${ROOT_PTNAME}" == "" ];then
+    echo "Cannot find the partition corresponding to the root file system!"
+    exit 1
+fi
+
+# Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
+case ${ROOT_PTNAME} in
+       mmcblk?p[1-4]) EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')" ;;
+    [hsv]d[a-z][1-4]) EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')" ;;
+                   *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+                      exit 1
+                      ;;
+esac
 P4_PATH="${PWD}"
 
 if [ -f ${ENV_ARMBIAN_FILE} ]; then
