Optimize code display

diff --git a/build-armbian/common-files/rootfs/usr/sbin/armbian-ddbr b/build-armbian/common-files/rootfs/usr/sbin/armbian-ddbr
--- a/build-armbian/common-files/rootfs/usr/sbin/armbian-ddbr
+++ b/build-armbian/common-files/rootfs/usr/sbin/armbian-ddbr
@@ -1,5 +1,6 @@
 #!/bin/bash
-#=========================================================================
+#===========================================================================
+#
 # This file is licensed under the terms of the GNU General Public
 # License version 2. This program is licensed "as is" without any
 # warranty of any kind, whether express or implied.
@@ -13,8 +14,9 @@
 # Copyright (C) 2021- https://github.com/ophub/amlogic-s9xxx-armbian
 #
 # Command: armbian-ddbr
-#=========================================================================
-
+#
+#========================= Set default parameters ==========================
+#
 # Set font color
 blue_font_prefix="\033[94m"
 purple_font_prefix="\033[95m"
@@ -27,47 +29,61 @@ STEPS="[${purple_font_prefix}STEPS${font_color_suffix}]"
 SUCCESS="[${green_font_prefix}SUCCESS${font_color_suffix}]"
 OPT="[${yellow_font_prefix}OPT${font_color_suffix}]"
 ERROR="[${red_font_prefix}ERROR${font_color_suffix}]"
+#
+# Check the output path
+out_path="/ddbr"
 # File name for backup/restore
 ddbr_image="BACKUP-arm-64-emmc.img.gz"
 # Need remaining space, unit: GB
 need_space="2"
-# Get device name
-mydevice_name=$(cat /proc/device-tree/model | tr -d '\000')
+#
+#===========================================================================
 
-# Find the EMMC drive
-emmc="$(lsblk -l -o NAME | grep -oE "mmcblk[0-9]boot0" | sort | uniq | sed "s/boot0//g")"
-if [[ "${emmc}" == "" ]]; then
-    echo "No emmc can be found to install the openwrt system!"
+# Encountered a serious error, abort the script execution
+error_msg() {
+    echo -e " ${ERROR} ${1}"
     exit 1
-fi
+}
 
-# Find the partition where root is located
-root_devname=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print substr($3, 1, length($3)-2)}')
-if lsblk -l | grep -E "^${root_devname}boot0" >/dev/null; then
-    echo "You are running in emmc mode, please boot system with TF/SD/USB!"
-    exit 1
-fi
+# Check emmc
+do_checkemmc() {
+    # Get device name
+    mydevice_name="$(cat /proc/device-tree/model | tr -d '\000')"
+    echo -e "${INFO} The device name: [ ${mydevice_name} ]"
 
-# Check the output path
-out_path="/ddbr"
-[ -d "${out_path}" ] || mkdir -p ${out_path}
+    # Find the EMMC drive
+    emmc="$(lsblk -l -o NAME | grep -oE "mmcblk[0-9]boot0" | sort | uniq | sed "s/boot0//g")"
+    if [[ "${emmc}" == "" ]]; then
+        error_msg "No emmc can be found to install the openwrt system!"
+    fi
+    echo -e "${INFO} The device EMMC name: [ /dev/${emmc} ]"
 
-# Check emmc partition size
-dev_intsize="$(fdisk -s /dev/${emmc})"
-[ -z "$(echo "${dev_intsize}" | sed -n "/^[0-9]\+$/p")" ] && echo -e "${ERROR} Unable to get EMMC size." && exit 1
+    # Find the partition where root is located
+    root_devname="$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print substr($3, 1, length($3)-2)}')"
+    if lsblk -l | grep -E "^${root_devname}boot0" >/dev/null; then
+        error_msg "You are running in emmc mode, please boot system with TF/SD/USB!"
+    fi
+
+    # Check emmc partition size
+    dev_intsize="$(fdisk -s /dev/${emmc})"
+    [ -z "$(echo "${dev_intsize}" | sed -n "/^[0-9]\+$/p")" ] && error_msg "Unable to get EMMC size."
+    echo -e "${INFO} The device EMMC size: [ $(($dev_intsize / 1024 / 1024))GB ]"
+
+    # check directory
+    [ -d "${out_path}" ] || mkdir -p ${out_path}
+    echo -e "${INFO} The ddbr file path: [ ${out_path}/${ddbr_image} ]\n"
+}
 
 # Check the remaining space
 do_checkspace() {
+    # Check the remaining space capacity
     remaining_space="$(df -hT ${out_path} | grep '/dev/' | awk '{print $5}' | sed 's/.$//' | awk -F "." '{print $1}')"
-    if [ -z "$(echo "${remaining_space}" | sed -n "/^[0-9]\+$/p")" ]; then
-        echo -e "${ERROR} The path is not available, the remaining space cannot be obtained."
-        exit 1
+    if [[ -z "$(echo "${remaining_space}" | sed -n "/^[0-9]\+$/p")" ]]; then
+        error_msg "The path is not available, the remaining space cannot be obtained."
     fi
+    # Check if there is enough free space
     if [[ "${remaining_space}" -lt "${need_space}" ]]; then
-        echo -e "${ERROR} The remaining space is [ ${remaining_space} ] GB."
-        echo -e "It is recommended that the remaining space should not be less than [ ${need_space} ] GB."
-        echo -e "Please use the [ armbian-tf ] command to extended partition first."
-        exit 1
+        error_msg "The remaining space is [ ${remaining_space} ] Gb, and more than [ ${need_space} ] Gb space is required."
     fi
 }
 
@@ -75,33 +91,35 @@ do_checkspace() {
 do_backup() {
     echo -e "${STEPS} Start to backup the system in emmc."
     do_checkspace
-    echo -e "Saving and Compressing [ /dev/${emmc} ] to [ ${out_path}/${ddbr_image} ], Please wait..."
+    echo -e "${INFO} Saving and Compressing [ /dev/${emmc} ] to [ ${out_path}/${ddbr_image} ], Please wait..."
     rm -f ${out_path}/${ddbr_image} 2>/dev/null && sync
     dd if=/dev/${emmc} | pv -s ${dev_intsize}"K" | gzip >${out_path}/${ddbr_image}
     [ "$?" -eq "0" ] && sync && echo -e "${SUCCESS} Backup is complete."
+    sync && sleep 3
+    exit 0
 }
 
 # Restore the emmc system
 do_restore() {
     echo -e "${STEPS} Start to restore the system in emmc."
-    [ ! -f ${out_path}/${ddbr_image} ] && echo -e "${ERROR} The [ ${out_path}/${ddbr_image} ] File not found." && exit 1
-    echo -e "Restoring [ ${out_path}/${ddbr_image} ] to [ /dev/${emmc} ], Please wait..."
+    [ ! -f "${out_path}/${ddbr_image}" ] && error_msg "The [ ${out_path}/${ddbr_image} ] File not found."
+    echo -e "${INFO} Restoring [ ${out_path}/${ddbr_image} ] to [ /dev/${emmc} ], Please wait..."
     gunzip -c ${out_path}/${ddbr_image} | pv -s ${dev_intsize}"K" | dd of=/dev/${emmc}
     [ "$?" -eq "0" ] && sync && echo -e "${SUCCESS} Restore is complete."
+    sync && sleep 3
+    exit 0
 }
 
-# Output device information
 echo -e "${STEPS} Welcome to use the EMMC system backup/restore service."
-echo -e "${INFO} The device name: [ ${mydevice_name} ]"
-echo -e "${INFO} The device EMMC name: [ /dev/${emmc} ]"
-echo -e "${INFO} The device EMMC size: [ $(($dev_intsize / 1024 / 1024))GB ]"
-echo -e "${INFO} The ddbr file path: [ ${out_path}/${ddbr_image} ]\n"
-
-# Prompt the user to select backup/restore
+# Check script permission
+[[ "$(id -u)" == "0" ]] || error_msg "please run this script as root: [ sudo $0 ]"
+# Check emmc
+do_checkemmc
+# Prompt the user to select Backup/Restore
 echo -ne "${OPT} Do you want to backup or restore? Backup=(b) Restore=(r): "
 read br
-case ${br} in
-    b | B | backup) do_backup ;;
+case "${br}" in
+    b | B | backup)  do_backup ;;
     r | R | restore) do_restore ;;
-    *) exit 0 ;;
+    *)               exit 0 ;;
 esac
diff --git a/build-armbian/common-files/rootfs/usr/sbin/armbian-swap b/build-armbian/common-files/rootfs/usr/sbin/armbian-swap
--- a/build-armbian/common-files/rootfs/usr/sbin/armbian-swap
+++ b/build-armbian/common-files/rootfs/usr/sbin/armbian-swap
@@ -1,5 +1,6 @@
 #!/bin/bash
-#=========================================================================
+#===========================================================================
+#
 # This file is licensed under the terms of the GNU General Public
 # License version 2. This program is licensed "as is" without any
 # warranty of any kind, whether express or implied.
@@ -13,64 +14,62 @@
 #
 # Command: armbian-swap 1
 # The input parameter unit is GB, the default is 1
+#
 #=========================================================================
 
-# Set the swap size in GB
-my_swap_gb="${1}"
-format_gb="$(echo "${my_swap_gb}" | awk -F "." '{print $1}')"
-if [[ -n "$(echo "${format_gb}" | sed -n "/^[0-9]\+$/p")" ]]; then
-    swap_gb="${format_gb}"
-else
-    swap_gb="1"
-fi
-
-# Find the partition where root is located
-ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ]; then
-    echo "Cannot find the partition corresponding to the root file system!"
+# Encountered a serious error, abort the script execution
+error_msg() {
+    echo -e " [ERROR] ${1}"
     exit 1
-fi
+}
 
-# Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
-case ${ROOT_PTNAME} in
-mmcblk?p[1-4])
-    EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
-    PARTITION_NAME="p"
-    LB_PRE="EMMC_"
-    ;;
-[hsv]d[a-z][1-4])
-    EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
-    PARTITION_NAME=""
-    LB_PRE=""
-    ;;
-*)
-    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-    exit 1
-    ;;
-esac
+# Check disk
+do_checkdisk() {
+    # Find the partition where root is located
+    ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
+    if [ "${ROOT_PTNAME}" == "" ]; then
+        error_msg "Cannot find the partition corresponding to the root file system!"
+    fi
 
-# Find out if the extended partition is created using the armbian-TF command in TF/USB
-find_right_path="/mnt/${EMMC_NAME}${PARTITION_NAME}3"
-if [ -d "${find_right_path}" ]; then
-    PARTITION_PATH="${find_right_path}"
-else
-    PARTITION_PATH="/mnt"
-fi
+    # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
+    case "${ROOT_PTNAME}" in
+    mmcblk?p[1-4])
+        EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')"
+        PARTITION_NAME="p"
+        LB_PRE="EMMC_"
+        ;;
+    [hsv]d[a-z][1-4])
+        EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')"
+        PARTITION_NAME=""
+        LB_PRE=""
+        ;;
+    *)
+        error_msg "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+        ;;
+    esac
 
-available_space="$(df -hT ${PARTITION_PATH} | grep '/dev/' | awk '{print $5}' | sed 's/.$//' | awk -F "." '{print $1}')"
-if [ -z "$(echo "${available_space}" | sed -n "/^[0-9]\+$/p")" ]; then
-    echo -e "The path is not available, the remaining space cannot be obtained."
-    exit 1
-fi
-if [[ "${available_space}" -lt "${swap_gb}" ]]; then
-    echo -e "The remaining space is [ ${available_space} ] GB, and [ ${swap_gb} ] GB swap cannot be created."
-    exit 1
-fi
+    # Find out if the extended partition is created using the armbian-TF command in TF/USB
+    find_right_path="/mnt/${EMMC_NAME}${PARTITION_NAME}3"
+    if [ -d "${find_right_path}" ]; then
+        PARTITION_PATH="${find_right_path}"
+    else
+        PARTITION_PATH="/mnt"
+    fi
 
-SWAP_PATH="${PARTITION_PATH}/.swap"
-mkdir -p ${SWAP_PATH} && sync
+    # Check if there is enough free space
+    available_space="$(df -hT ${PARTITION_PATH} | grep '/dev/' | awk '{print $5}' | sed 's/.$//' | awk -F "." '{print $1}')"
+    if [ -z "$(echo "${available_space}" | sed -n "/^[0-9]\+$/p")" ]; then
+        error_msg "The path is not available, the remaining space cannot be obtained."
+    fi
+    if [[ "${available_space}" -lt "${swap_gb}" ]]; then
+        error_msg "The remaining space is [ ${available_space} ] GB, and [ ${swap_gb} ] GB swap cannot be created."
+    fi
 
-echo -e "Prepare to create [ ${swap_gb} ] GB swap in the [ ${SWAP_PATH} ] directory."
+    # Check directory
+    SWAP_PATH="${PARTITION_PATH}/.swap"
+    mkdir -p ${SWAP_PATH} && sync
+    echo -e "Prepare to create [ ${swap_gb} ] GB swap in the [ ${SWAP_PATH} ] directory."
+}
 
 # delete current swap
 delete_current_swap() {
@@ -84,7 +83,7 @@ delete_current_swap() {
 # create new swap
 create_new_swap() {
     echo -e "Start creating a new swap..."
-    dd_count=$((1000000 * ${swap_gb}))
+    dd_count="$((1000000 * ${swap_gb}))"
     echo -e "The swap size is: [ ${swap_gb} ] GB, Please wait..."
     dd if=/dev/zero of=${SWAP_PATH}/swapfile bs=1024 count=${dd_count} conv=fsync && sync
     chmod 600 ${SWAP_PATH}/swapfile
@@ -98,12 +97,34 @@ create_new_swap() {
     echo -e "Current swap: \n$(cat /proc/swaps) \n"
 }
 
-current_swap="$(free -m | sed -n '$p' | awk '{print $2}' | echo $(xargs))"
-if [ "${current_swap}" -gt "0" ]; then
-    delete_current_swap ${current_swap}
-    create_new_swap ${swap_gb}
-else
-    create_new_swap ${swap_gb}
-fi
-sync
-exit 0
+# Check swap
+do_checkswap() {
+    # Set the swap size in GB
+    my_swap_gb="${1}"
+    format_gb="$(echo "${my_swap_gb}" | awk -F "." '{print $1}')"
+    if [[ -n "$(echo "${format_gb}" | sed -n "/^[0-9]\+$/p")" ]]; then
+        swap_gb="${format_gb}"
+    else
+        swap_gb="1"
+    fi
+
+    # Check disk
+    do_checkdisk
+
+    # manage swap
+    current_swap="$(free -m | sed -n '$p' | awk '{print $2}' | echo $(xargs))"
+    if [[ "${current_swap}" -gt "0" ]]; then
+        delete_current_swap ${current_swap}
+        create_new_swap ${swap_gb}
+    else
+        create_new_swap ${swap_gb}
+    fi
+    sync && sleep 3
+    exit 0
+}
+
+echo -e "Welcome to use swap management tool."
+# Check script permission
+[[ "$(id -u)" == "0" ]] || error_msg "please run this script as root: [ sudo $0 ]"
+# Check swap
+do_checkswap "${@}"
