Adjust the uInitrd file usage strategy

diff --git a/build-armbian/common-files/files/usr/sbin/armbian-tf b/build-armbian/common-files/files/usr/sbin/armbian-tf
--- a/build-armbian/common-files/files/usr/sbin/armbian-tf
+++ b/build-armbian/common-files/files/usr/sbin/armbian-tf
@@ -21,9 +21,10 @@ echo -e "${STEPS} Try to create a shared partition..."
 echo -ne "${STEPS} This operation will clear the data in the remaining space, are you sure to continue? y/n [y]\b\b"
 read yn
 case $yn in
-     n*|N*) echo -e "${ERROR} You aborted the operation!"
-            exit 1
-            ;;
+n* | N*)
+    echo -e "${ERROR} You aborted the operation!"
+    exit 1
+    ;;
 esac
 
 # Find the partition where root is located
@@ -35,21 +36,24 @@ fi
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
-       mmcblk?p[1-4]) DISK_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
-                      PT_PRE="${DISK_NAME}p"
-                      LB_PRE="EMMC_"
-                      ;;
-    [hsv]d[a-z][1-4]) DISK_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
-                      PT_PRE="${DISK_NAME}"
-                      LB_PRE=""
-                      ;;
-                   *) echo -e "${ERROR} Unable to recognize the disk type of ${ROOT_PTNAME}!"
-                      exit 1
-                      ;;
+mmcblk?p[1-4])
+    DISK_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
+    PT_PRE="${DISK_NAME}p"
+    LB_PRE="EMMC_"
+    ;;
+[hsv]d[a-z][1-4])
+    DISK_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
+    PT_PRE="${DISK_NAME}"
+    LB_PRE=""
+    ;;
+*)
+    echo -e "${ERROR} Unable to recognize the disk type of ${ROOT_PTNAME}!"
+    exit 1
+    ;;
 esac
 
 # Get the starting position of the p3 partition
-START_P3=$( fdisk -l | grep "${ROOT_PTNAME}" | sed -n '$p' | awk '{print $3}' | echo $(($(xargs)+1)) )
+START_P3=$(fdisk -l | grep "${ROOT_PTNAME}" | sed -n '$p' | awk '{print $3}' | echo $(($(xargs) + 1)))
 if [[ -z "${START_P3}" || -z "$(echo ${START_P3} | sed -n "/^[0-9]\+$/p")" ]]; then
     echo -e "${ERROR} Unable to get starting position!"
     exit 1
@@ -57,7 +61,7 @@ fi
 TOTAL_SIZE=$(lsblk -l -b -o NAME,SIZE | awk "\$1 ~ /^${DISK_NAME}\$/ {print \$2}")
 END_P3=$((TOTAL_SIZE / 512 - 1))
 
-cat > /tmp/fdisk.script <<EOF
+cat >/tmp/fdisk.script <<EOF
 n
 p
 3
@@ -72,22 +76,21 @@ EOF
 sync
 
 echo -e "${STEPS} Fdisk starting ... "
-fdisk /dev/${DISK_NAME} < /tmp/fdisk.script 2>/dev/null
-if [ $? -ne 0 ];then
-	echo -e "${ERROR} fdisk failed!"
-	exit 1
+fdisk /dev/${DISK_NAME} </tmp/fdisk.script 2>/dev/null
+if [ $? -ne 0 ]; then
+    echo -e "${ERROR} fdisk failed!"
+    exit 1
 fi
 sync
 
 echo -e "${STEPS} Create shared filesystem ... "
 mkdir -p /mnt/${PT_PRE}3 && sync
-mkfs.ext4  -F -L "${LB_PRE}SHARED" "/dev/${PT_PRE}3"
+mkfs.ext4 -F -L "${LB_PRE}SHARED" "/dev/${PT_PRE}3"
 mount -t ext4 "/dev/${PT_PRE}3" "/mnt/${PT_PRE}3"
-echo "/dev/${PT_PRE}3 /mnt/${PT_PRE}3 ext4 defaults 0 0" >> /etc/fstab
+echo "/dev/${PT_PRE}3 /mnt/${PT_PRE}3 ext4 defaults 0 0" >>/etc/fstab
 sync
 
 echo -e "${SUCCESS} Create partition successfully, mount it in [ /mnt/${PT_PRE}3 ]"
 rm -f /usr/sbin/armbian-tf 2>/dev/null && sync
 sync
 exit 0
-
diff --git a/build-armbian/common-files/files/usr/sbin/armbian-update b/build-armbian/common-files/files/usr/sbin/armbian-update
--- a/build-armbian/common-files/files/usr/sbin/armbian-update
+++ b/build-armbian/common-files/files/usr/sbin/armbian-update
@@ -50,18 +50,19 @@ echo -e "Start update the armbian kernel."
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ];then
+if [ "${ROOT_PTNAME}" == "" ]; then
     echo "Cannot find the partition corresponding to the root file system!"
     exit 1
 fi
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
-       mmcblk?p[1-4]) EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')" ;;
-    [hsv]d[a-z][1-4]) EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')" ;;
-                   *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-                      exit 1
-                      ;;
+mmcblk?p[1-4]) EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')" ;;
+[hsv]d[a-z][1-4]) EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')" ;;
+*)
+    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+    exit 1
+    ;;
 esac
 P4_PATH="${PWD}"
 
@@ -70,23 +71,22 @@ if [ -f "${ENV_ARMBIAN_FILE}" ]; then
     UBOOT_OVERLOAD="${UBOOT_OVERLOAD}"
     MAINLINE_UBOOT="${MAINLINE_UBOOT}"
 else
-    echo  "${ENV_ARMBIAN_FILE} file is missing!"
+    echo "${ENV_ARMBIAN_FILE} file is missing!"
     exit 1
 fi
 
 # Check 3 kernel files
-if  [ $( ls ${P4_PATH}/*${INPUTS_KERNEL}*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -lt 3 ]; then
-
+if [ $(ls ${P4_PATH}/*${INPUTS_KERNEL}*.tar.gz -l 2>/dev/null | grep "^-" | wc -l) -lt 3 ]; then
     if [[ -z "${INPUTS_KERNEL}" ]]; then
-        LATEST_VERSION_K4_LATEST=$(curl -s "${SERVER_KERNEL_URL}" | grep "name" | grep -oE "5.4.[0-9]+"  | sed -e "s/5.4.//g" | sort -n | sed -n '$p')
+        LATEST_VERSION_K4_LATEST=$(curl -s "${SERVER_KERNEL_URL}" | grep "name" | grep -oE "5.4.[0-9]+" | sed -e "s/5.4.//g" | sort -n | sed -n '$p')
         LATEST_VERSION_K4="5.4.${LATEST_VERSION_K4_LATEST}"
 
-        LATEST_VERSION_K10_LATEST=$(curl -s "${SERVER_KERNEL_URL}" | grep "name" | grep -oE "5.10.[0-9]+"  | sed -e "s/5.10.//g" | sort -n | sed -n '$p')
+        LATEST_VERSION_K10_LATEST=$(curl -s "${SERVER_KERNEL_URL}" | grep "name" | grep -oE "5.10.[0-9]+" | sed -e "s/5.10.//g" | sort -n | sed -n '$p')
         LATEST_VERSION_K10="5.10.${LATEST_VERSION_K10_LATEST}"
 
-        echo  "The latest version on the server is: [ ${LATEST_VERSION_K4} / ${LATEST_VERSION_K10} ]"
-        echo  "Please enter the kernel version number, such as: ${LATEST_VERSION_K4}"
-        read  KERNEL_NUM
+        echo "The latest version on the server is: [ ${LATEST_VERSION_K4} / ${LATEST_VERSION_K10} ]"
+        echo "Please enter the kernel version number, such as: ${LATEST_VERSION_K4}"
+        read KERNEL_NUM
         [ -n "${KERNEL_NUM}" ] || KERNEL_NUM="${LATEST_VERSION_K4}"
     else
         KERNEL_NUM="${INPUTS_KERNEL}"
@@ -135,18 +135,17 @@ if  [ $( ls ${P4_PATH}/*${INPUTS_KERNEL}*.tar.gz -l 2>/dev/null | grep "^-" | wc
     sync
 fi
 
-if  [ $( ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; then
-
-    if  [ $( ls ${P4_PATH}/boot-*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 1 ]; then
-        build_boot=$( ls ${P4_PATH}/boot-*.tar.gz | head -n 1 ) && build_boot=${build_boot##*/}
+if [ $(ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l) -ge 3 ]; then
+    if [ $(ls ${P4_PATH}/boot-*.tar.gz -l 2>/dev/null | grep "^-" | wc -l) -ge 1 ]; then
+        build_boot=$(ls ${P4_PATH}/boot-*.tar.gz | head -n 1) && build_boot=${build_boot##*/}
         echo -e "Update using [ ${build_boot} ] files. Please wait a moment ..."
-        flippy_version=${build_boot/boot-/} && flippy_version=${flippy_version/.tar.gz/}
-        kernel_version=$(echo ${flippy_version} | grep -oE '^[1-9].[0-9]{1,3}.[0-9]+')
+        custom_kernel_name=${build_boot/boot-/} && custom_kernel_name=${custom_kernel_name/.tar.gz/}
+        kernel_version=$(echo ${custom_kernel_name} | grep -oE '^[1-9].[0-9]{1,3}.[0-9]+')
         kernel_vermaj=$(echo ${kernel_version} | grep -oE '^[1-9].[0-9]{1,3}')
         k510_ver=${kernel_vermaj%%.*}
         k510_maj=${kernel_vermaj##*.}
-        if  [ ${k510_ver} -eq "5" ]; then
-            if  [ "${k510_maj}" -ge "10" ]; then
+        if [ ${k510_ver} -eq "5" ]; then
+            if [ "${k510_maj}" -ge "10" ]; then
                 K510=1
             else
                 K510=0
@@ -160,14 +159,14 @@ if  [ $( ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; th
         die "Have no boot-*.tar.gz file found in the ${P4_PATH} directory."
     fi
 
-    if  [ -f ${P4_PATH}/dtb-amlogic-${flippy_version}.tar.gz ]; then
-        build_dtb="dtb-amlogic-${flippy_version}.tar.gz"
+    if [ -f ${P4_PATH}/dtb-amlogic-${custom_kernel_name}.tar.gz ]; then
+        build_dtb="dtb-amlogic-${custom_kernel_name}.tar.gz"
     else
         die "Have no dtb-amlogic-*.tar.gz file found in the ${P4_PATH} directory."
     fi
 
-    if  [ -f ${P4_PATH}/modules-${flippy_version}.tar.gz ]; then
-        build_modules="modules-${flippy_version}.tar.gz"
+    if [ -f ${P4_PATH}/modules-${custom_kernel_name}.tar.gz ]; then
+        build_modules="modules-${custom_kernel_name}.tar.gz"
     else
         die "Have no modules-*.tar.gz file found in the ${P4_PATH} directory."
     fi
@@ -177,7 +176,7 @@ if  [ $( ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; th
     boot: ${build_boot} \n \
     dtb: ${build_dtb} \n \
     modules: ${build_modules} \n \
-    flippy_version: ${flippy_version} \n \
+    custom_kernel_name: ${custom_kernel_name} \n \
     kernel_version: ${kernel_version} \n \
     K510: ${K510}"
 
@@ -190,8 +189,8 @@ MODULES_OLD=$(ls /lib/modules/ 2>/dev/null)
 VERSION_OLD=$(echo ${MODULES_OLD} | grep -oE '^[1-9].[0-9]{1,3}' 2>/dev/null)
 VERSION_ver=${VERSION_OLD%%.*}
 VERSION_maj=${VERSION_OLD##*.}
-if  [ ${VERSION_ver} -eq "5" ]; then
-    if  [ "${VERSION_maj}" -ge "10" ]; then
+if [ ${VERSION_ver} -eq "5" ]; then
+    if [ "${VERSION_maj}" -ge "10" ]; then
         V510=1
     else
         V510=0
@@ -259,19 +258,19 @@ if [ "${V510}" -lt "${K510}" ]; then
     fi
 fi
 
-echo -e "Unpack [ ${flippy_version} ] related files ..."
+echo -e "Unpack [ ${custom_kernel_name} ] related files ..."
 
 # 01. for /boot five files
 rm -f /boot/config-* /boot/initrd.img-* /boot/System.map-* /boot/uInitrd-* /boot/vmlinuz-* 2>/dev/null && sync
 rm -f /boot/uInitrd /boot/zImage 2>/dev/null && sync
 tar -xzf ${P4_PATH}/${build_boot} -C /boot && sync
 
-if [[ -f "/boot/uInitrd-${flippy_version}" ]]; then
+if [[ -f "/boot/uInitrd-${custom_kernel_name}" ]]; then
     i=1
     max_try=10
     while [ "${i}" -le "${max_try}" ]; do
-        cp -f /boot/uInitrd-${flippy_version} /boot/uInitrd 2>/dev/null && sync
-        uInitrd_original=$(md5sum /boot/uInitrd-${flippy_version} | awk '{print $1}')
+        cp -f /boot/uInitrd-${custom_kernel_name} /boot/uInitrd 2>/dev/null && sync
+        uInitrd_original=$(md5sum /boot/uInitrd-${custom_kernel_name} | awk '{print $1}')
         uInitrd_new=$(md5sum /boot/uInitrd | awk '{print $1}')
         if [[ "${uInitrd_original}" == "${uInitrd_new}" ]]; then
             break
@@ -281,17 +280,17 @@ if [[ -f "/boot/uInitrd-${flippy_version}" ]]; then
             continue
         fi
     done
-    [ "${i}" -eq "10" ] && die "/boot/uInitrd-${flippy_version} file copy failed."
+    [ "${i}" -eq "10" ] && die "/boot/uInitrd-${custom_kernel_name} file copy failed."
 else
-    die "/boot/uInitrd-${flippy_version} file is missing."
+    die "/boot/uInitrd-${custom_kernel_name} file is missing."
 fi
 
-if [[ -f "/boot/vmlinuz-${flippy_version}" ]]; then
+if [[ -f "/boot/vmlinuz-${custom_kernel_name}" ]]; then
     i=1
     max_try=10
     while [ "${i}" -le "${max_try}" ]; do
-        cp -f /boot/vmlinuz-${flippy_version} /boot/zImage 2>/dev/null && sync
-        vmlinuz_original=$(md5sum /boot/vmlinuz-${flippy_version} | awk '{print $1}')
+        cp -f /boot/vmlinuz-${custom_kernel_name} /boot/zImage 2>/dev/null && sync
+        vmlinuz_original=$(md5sum /boot/vmlinuz-${custom_kernel_name} | awk '{print $1}')
         vmlinuz_new=$(md5sum /boot/zImage | awk '{print $1}')
         if [[ "${vmlinuz_original}" == "${vmlinuz_new}" ]]; then
             break
@@ -301,28 +300,28 @@ if [[ -f "/boot/vmlinuz-${flippy_version}" ]]; then
             continue
         fi
     done
-    [ "${i}" -eq "10" ] && die "/boot/vmlinuz-${flippy_version} file copy failed."
+    [ "${i}" -eq "10" ] && die "/boot/vmlinuz-${custom_kernel_name} file copy failed."
 else
-    die "/boot/vmlinuz-${flippy_version} file is missing."
+    die "/boot/vmlinuz-${custom_kernel_name} file is missing."
 fi
 
-[ -f "/boot/config-${flippy_version}" ] || die "/boot/config-${flippy_version} file is missing."
-[ -f "/boot/System.map-${flippy_version}" ] || die "/boot/System.map-${flippy_version} file is missing."
+[ -f "/boot/config-${custom_kernel_name}" ] || die "/boot/config-${custom_kernel_name} file is missing."
+[ -f "/boot/System.map-${custom_kernel_name}" ] || die "/boot/System.map-${custom_kernel_name} file is missing."
 
 echo -e "02.01 Unpack [ ${build_boot} ] complete."
 sleep 3
 
 # 02 for /boot/dtb/amlogic/*
 tar -xzf ${P4_PATH}/${build_dtb} -C /boot/dtb/amlogic && sync
-[ "$( ls /boot/dtb/amlogic -l 2>/dev/null | grep "^-" | wc -l )" -ge "10" ] || die "/boot/dtb/amlogic file is missing."
+[ "$(ls /boot/dtb/amlogic -l 2>/dev/null | grep "^-" | wc -l)" -ge "10" ] || die "/boot/dtb/amlogic file is missing."
 echo -e "02.02 Unpack [ ${build_dtb} ] complete."
 sleep 3
 
 # 03 for /lib/modules/*
 rm -rf /lib/modules/* 2>/dev/null && sync
 tar -xzf ${P4_PATH}/${build_modules} -C /lib/modules && sync
-( cd /lib/modules/${flippy_version} && echo "build source" | xargs rm -f )
-[[ -d "/lib/modules/${flippy_version}" ]] || die "/lib/modules/${flippy_version} kernel folder is missing."
+(cd /lib/modules/${custom_kernel_name} && echo "build source" | xargs rm -f)
+[[ -d "/lib/modules/${custom_kernel_name}" ]] || die "/lib/modules/${custom_kernel_name} kernel folder is missing."
 echo -e "02.03 Unpack [ ${build_modules} ] complete."
 sleep 3
 
@@ -330,9 +329,9 @@ rm -f ${P4_PATH}/dtb-amlogic-*.tar.gz ${P4_PATH}/boot-*.tar.gz ${P4_PATH}/module
 
 # 04 Update
 sed -i '/KERNEL_VERSION/d' ${ENV_ARMBIAN_FILE} 2>/dev/null
-echo "KERNEL_VERSION='${kernel_version}'" >> ${ENV_ARMBIAN_FILE} 2>/dev/null
+echo "KERNEL_VERSION='${kernel_version}'" >>${ENV_ARMBIAN_FILE} 2>/dev/null
 sed -i '/K510/d' ${ENV_ARMBIAN_FILE} 2>/dev/null
-echo "K510='${K510}'" >> ${ENV_ARMBIAN_FILE} 2>/dev/null
+echo "K510='${K510}'" >>${ENV_ARMBIAN_FILE} 2>/dev/null
 
 sync
 wait
@@ -341,4 +340,3 @@ echo "Successfully updated, automatic restarting..."
 sleep 3
 reboot
 exit 0
-
