armbian-update: unified error output

diff --git a/build-armbian/common-files/files/usr/sbin/armbian-update b/build-armbian/common-files/files/usr/sbin/armbian-update
--- a/build-armbian/common-files/files/usr/sbin/armbian-update
+++ b/build-armbian/common-files/files/usr/sbin/armbian-update
@@ -17,6 +17,11 @@
 #==================================================================================================================================
 
 echo -e "Ready to update, please wait..."
+# Encountered a serious error, abort the script execution
+die() {
+    echo -e " [Error] ${1}"
+    exit 1
+}
 
 # Receive one-key command related parameters
 # Specify the kernel, such as: 5.10.70
@@ -26,7 +31,7 @@ elif [[ "$(ls *.tar.gz -l 2>/dev/null | grep "^-" | wc -l)" -gt "3" ]]; then
     try_boot=$(ls boot-*.tar.gz 2>/dev/null | head -n 1 | grep -oE '[1-9].[0-9]{1,3}.[0-9]+')
     [ -n "${try_boot}" ] && INPUTS_KERNEL="${try_boot}"
 else
-    INPUTS_KERNEL=""
+    die "Please enter the kernel version number, such as: armbian-update 5.4.160"
 fi
 
 # Specify version branch, such as: stable
@@ -49,18 +54,9 @@ SERVER_KERNEL_URL="https://api.github.com/repos/ophub/kernel/contents/pub/${vers
 GITHUB_RAW="https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian"
 ENV_ARMBIAN_FILE="/etc/armbian-aml-release"
 
-# Encountered a serious error, abort the script execution
-die() {
-    echo -e " [Error] ${1}"
-    exit 1
-}
-
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ]; then
-    echo "Cannot find the partition corresponding to the root file system!"
-    exit 1
-fi
+[ -z "${ROOT_PTNAME}" ] && die "Cannot find the partition corresponding to the root file system!"
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
@@ -71,8 +67,7 @@ mmcblk?p[1-4])
     EMMC_NAME="$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')"
     ;;
 *)
-    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-    exit 1
+    die "Unable to recognize the disk type of ${ROOT_PTNAME}!"
     ;;
 esac
 P4_PATH="${PWD}"
@@ -82,8 +77,7 @@ if [ -f "${ENV_ARMBIAN_FILE}" ]; then
     UBOOT_OVERLOAD="${UBOOT_OVERLOAD}"
     MAINLINE_UBOOT="${MAINLINE_UBOOT}"
 else
-    echo "${ENV_ARMBIAN_FILE} file is missing!"
-    exit 1
+    die "${ENV_ARMBIAN_FILE} file is missing!"
 fi
 
 # Check 3 kernel files
@@ -199,8 +193,7 @@ if [ $(ls ${P4_PATH}/*${INPUTS_KERNEL}*.tar.gz -l 2>/dev/null | grep "^-" | wc -
         build_header=""
     fi
 else
-    echo -e "Please upload the kernel files to [ ${P4_PATH} ], then run [ $0 ] again."
-    exit 1
+    die "Please upload the kernel files to [ ${P4_PATH} ], then run [ $0 ] again."
 fi
 
 MODULES_OLD=$(ls /lib/modules/ 2>/dev/null)
