Adjust release file

diff --git a/build-armbian/common-files/files/usr/sbin/armbian-update b/build-armbian/common-files/files/usr/sbin/armbian-update
--- a/build-armbian/common-files/files/usr/sbin/armbian-update
+++ b/build-armbian/common-files/files/usr/sbin/armbian-update
@@ -26,17 +26,17 @@ die() {
 # Receive one-key command related parameters
 # Specify the kernel, such as: 5.10.70
 if [ -n "${1}" ]; then
-    INPUTS_KERNEL="${1}"
+    inputs_kernel="${1}"
 elif [[ "$(ls *.tar.gz -l 2>/dev/null | grep "^-" | wc -l)" -gt "3" ]]; then
     try_boot=$(ls boot-*.tar.gz 2>/dev/null | head -n 1 | grep -oE '[1-9].[0-9]{1,3}.[0-9]+')
-    [ -n "${try_boot}" ] && INPUTS_KERNEL="${try_boot}"
+    [ -n "${try_boot}" ] && inputs_kernel="${try_boot}"
 else
     die "Please enter the kernel version number, such as: armbian-update 5.4.160"
 fi
 
 # Specify version branch, such as: stable
-ARR_BRANCH=("stable" "dev")
-if [[ -n "${2}" && -n "$(echo "${ARR_BRANCH[@]}" | grep -w "${2}")" ]]; then
+arr_branch=("stable" "dev" "eol")
+if [[ -n "${2}" && -n "$(echo "${arr_branch[@]}" | grep -w "${2}")" ]]; then
     version_branch="${2}"
 else
     version_branch="stable"
@@ -44,15 +44,15 @@ fi
 
 # Specify whether to brush into the mainline u-boot, such as: yes
 if [[ "${3}" == "no" ]]; then
-    AUTO_MAINLINE_UBOOT="no"
+    auto_mainline_uboot="no"
 else
-    AUTO_MAINLINE_UBOOT="yes"
+    auto_mainline_uboot="yes"
 fi
 
 # Set default value
-SERVER_KERNEL_URL="https://api.github.com/repos/ophub/kernel/contents/pub/${version_branch}"
-GITHUB_RAW="https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian"
-ENV_ARMBIAN_FILE="/etc/armbian-aml-release"
+kernel_repo="https://api.github.com/repos/ophub/kernel/contents/pub/${version_branch}"
+depends_repo="https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian"
+ophub_release_file="/etc/ophub-release"
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
@@ -72,75 +72,75 @@ mmcblk?p[1-4])
 esac
 P4_PATH="${PWD}"
 
-if [ -f "${ENV_ARMBIAN_FILE}" ]; then
-    source "${ENV_ARMBIAN_FILE}" 2>/dev/null
+if [ -f "${ophub_release_file}" ]; then
+    source "${ophub_release_file}" 2>/dev/null
     UBOOT_OVERLOAD="${UBOOT_OVERLOAD}"
     MAINLINE_UBOOT="${MAINLINE_UBOOT}"
 else
-    die "${ENV_ARMBIAN_FILE} file is missing!"
+    die "${ophub_release_file} file is missing!"
 fi
 
 # Check 3 kernel files
-if [[ "$(ls ${P4_PATH}/*${INPUTS_KERNEL}*.tar.gz -l 2>/dev/null | grep "^-" | wc -l)" -lt "3" ]]; then
-    if [[ -z "${INPUTS_KERNEL}" ]]; then
-        LATEST_VERSION_K4_LATEST=$(curl -s "${SERVER_KERNEL_URL}" | grep "name" | grep -oE "5.4.[0-9]+" | sed -e "s/5.4.//g" | sort -n | sed -n '$p')
-        LATEST_VERSION_K4="5.4.${LATEST_VERSION_K4_LATEST}"
-        echo "Please enter the kernel version number, such as: ${LATEST_VERSION_K4}"
-        read KERNEL_NUM
-        if [ -n "${KERNEL_NUM}" ]; then
-            INPUTS_KERNEL="${KERNEL_NUM}"
+if [[ "$(ls ${P4_PATH}/*${inputs_kernel}*.tar.gz -l 2>/dev/null | grep "^-" | wc -l)" -lt "3" ]]; then
+    if [[ -z "${inputs_kernel}" ]]; then
+        kernel_latest_num=$(curl -s "${kernel_repo}" | grep "name" | grep -oE "5.4.[0-9]+" | sed -e "s/5.4.//g" | sort -n | sed -n '$p')
+        kernel_latest_k4="5.4.${kernel_latest_num}"
+        echo "Please enter the kernel version number, such as: ${kernel_latest_k4}"
+        read kernel_num
+        if [ -n "${kernel_num}" ]; then
+            inputs_kernel="${kernel_num}"
         else
-            INPUTS_KERNEL="${LATEST_VERSION_K4}"
+            inputs_kernel="${kernel_latest_k4}"
         fi
     fi
 
-    echo -e "Kernel version: ${INPUTS_KERNEL}"
+    echo -e "Kernel version: ${inputs_kernel}"
     echo -e "Start downloading the kernel from [ github.com/ophub/kernel/tree/main/pub/${version_branch} ] to [ ${P4_PATH} ]..."
 
     # Delete tmp files
-    rm -f ${P4_PATH}/*${INPUTS_KERNEL}*.tar.gz 2>/dev/null
+    rm -f ${P4_PATH}/*${inputs_kernel}*.tar.gz 2>/dev/null
     sync
 
     # Download boot file
-    SERVER_KERNEL_BOOT="$(curl -s "${SERVER_KERNEL_URL}/${INPUTS_KERNEL}" | grep "download_url" | grep -o "https.*/boot-.*.tar.gz" | head -n 1)"
-    SERVER_KERNEL_BOOT_NAME="${SERVER_KERNEL_BOOT##*/}"
-    SERVER_KERNEL_BOOT_NAME="${SERVER_KERNEL_BOOT_NAME//%2B/+}"
-    wget -c "${SERVER_KERNEL_BOOT}" -O "${P4_PATH}/${SERVER_KERNEL_BOOT_NAME}" >/dev/null 2>&1 && sync
-    if [[ "$?" -eq "0" && -s "${P4_PATH}/${SERVER_KERNEL_BOOT_NAME}" ]]; then
+    server_kernel_boot="$(curl -s "${kernel_repo}/${inputs_kernel}" | grep "download_url" | grep -o "https.*/boot-.*.tar.gz" | head -n 1)"
+    server_kernel_boot_name="${server_kernel_boot##*/}"
+    server_kernel_boot_name="${server_kernel_boot_name//%2B/+}"
+    wget -c "${server_kernel_boot}" -O "${P4_PATH}/${server_kernel_boot_name}" >/dev/null 2>&1 && sync
+    if [[ "$?" -eq "0" && -s "${P4_PATH}/${server_kernel_boot_name}" ]]; then
         echo -e "01.01 The boot file download complete."
     else
         die "01.01 The boot file failed to download."
     fi
 
     # Download dtb file
-    SERVER_KERNEL_DTB="$(curl -s "${SERVER_KERNEL_URL}/${INPUTS_KERNEL}" | grep "download_url" | grep -o "https.*/dtb-amlogic-.*.tar.gz" | head -n 1)"
-    SERVER_KERNEL_DTB_NAME="${SERVER_KERNEL_DTB##*/}"
-    SERVER_KERNEL_DTB_NAME="${SERVER_KERNEL_DTB_NAME//%2B/+}"
-    wget -c "${SERVER_KERNEL_DTB}" -O "${P4_PATH}/${SERVER_KERNEL_DTB_NAME}" >/dev/null 2>&1 && sync
-    if [[ "$?" -eq "0" && -s "${P4_PATH}/${SERVER_KERNEL_DTB_NAME}" ]]; then
+    server_kernel_dtb="$(curl -s "${kernel_repo}/${inputs_kernel}" | grep "download_url" | grep -o "https.*/dtb-amlogic-.*.tar.gz" | head -n 1)"
+    server_kernel_dtb_name="${server_kernel_dtb##*/}"
+    server_kernel_dtb_name="${server_kernel_dtb_name//%2B/+}"
+    wget -c "${server_kernel_dtb}" -O "${P4_PATH}/${server_kernel_dtb_name}" >/dev/null 2>&1 && sync
+    if [[ "$?" -eq "0" && -s "${P4_PATH}/${server_kernel_dtb_name}" ]]; then
         echo -e "01.02 The dtb file download complete."
     else
         die "01.02 The dtb file failed to download."
     fi
 
     # Download modules file
-    SERVER_KERNEL_MODULES="$(curl -s "${SERVER_KERNEL_URL}/${INPUTS_KERNEL}" | grep "download_url" | grep -o "https.*/modules-.*.tar.gz" | head -n 1)"
-    SERVER_KERNEL_MODULES_NAME="${SERVER_KERNEL_MODULES##*/}"
-    SERVER_KERNEL_MODULES_NAME="${SERVER_KERNEL_MODULES_NAME//%2B/+}"
-    wget -c "${SERVER_KERNEL_MODULES}" -O "${P4_PATH}/${SERVER_KERNEL_MODULES_NAME}" >/dev/null 2>&1 && sync
-    if [[ "$?" -eq "0" && -s "${P4_PATH}/${SERVER_KERNEL_MODULES_NAME}" ]]; then
+    server_kernel_modules="$(curl -s "${kernel_repo}/${inputs_kernel}" | grep "download_url" | grep -o "https.*/modules-.*.tar.gz" | head -n 1)"
+    server_kernel_modules_name="${server_kernel_modules##*/}"
+    server_kernel_modules_name="${server_kernel_modules_name//%2B/+}"
+    wget -c "${server_kernel_modules}" -O "${P4_PATH}/${server_kernel_modules_name}" >/dev/null 2>&1 && sync
+    if [[ "$?" -eq "0" && -s "${P4_PATH}/${server_kernel_modules_name}" ]]; then
         echo -e "01.03 The modules file download complete."
     else
         die "01.03 The modules file failed to download."
     fi
 
     # Download header file
-    SERVER_KERNEL_HEADER="$(curl -s "${SERVER_KERNEL_URL}/${INPUTS_KERNEL}" | grep "download_url" | grep -o "https.*/header-.*.tar.gz" | head -n 1)"
-    if [ -n "${SERVER_KERNEL_HEADER}" ]; then
-        SERVER_KERNEL_HEADER_NAME="${SERVER_KERNEL_HEADER##*/}"
-        SERVER_KERNEL_HEADER_NAME="${SERVER_KERNEL_HEADER_NAME//%2B/+}"
-        wget -c "${SERVER_KERNEL_HEADER}" -O "${P4_PATH}/${SERVER_KERNEL_HEADER_NAME}" >/dev/null 2>&1 && sync
-        if [[ "$?" -eq "0" && -s "${P4_PATH}/${SERVER_KERNEL_HEADER_NAME}" ]]; then
+    server_kernel_header="$(curl -s "${kernel_repo}/${inputs_kernel}" | grep "download_url" | grep -o "https.*/header-.*.tar.gz" | head -n 1)"
+    if [ -n "${server_kernel_header}" ]; then
+        server_kernel_header_name="${server_kernel_header##*/}"
+        server_kernel_header_name="${server_kernel_header_name//%2B/+}"
+        wget -c "${server_kernel_header}" -O "${P4_PATH}/${server_kernel_header_name}" >/dev/null 2>&1 && sync
+        if [[ "$?" -eq "0" && -s "${P4_PATH}/${server_kernel_header_name}" ]]; then
             echo -e "01.04 The header file download complete."
         else
             die "01.04 The header file failed to download."
@@ -150,9 +150,9 @@ if [[ "$(ls ${P4_PATH}/*${INPUTS_KERNEL}*.tar.gz -l 2>/dev/null | grep "^-" | wc
     sync
 fi
 
-if [ $(ls ${P4_PATH}/*${INPUTS_KERNEL}*.tar.gz -l 2>/dev/null | grep "^-" | wc -l) -ge 3 ]; then
-    if [ $(ls ${P4_PATH}/boot-${INPUTS_KERNEL}-*.tar.gz -l 2>/dev/null | grep "^-" | wc -l) -ge 1 ]; then
-        build_boot=$(ls ${P4_PATH}/boot-${INPUTS_KERNEL}-*.tar.gz | head -n 1) && build_boot=${build_boot##*/}
+if [ $(ls ${P4_PATH}/*${inputs_kernel}*.tar.gz -l 2>/dev/null | grep "^-" | wc -l) -ge 3 ]; then
+    if [ $(ls ${P4_PATH}/boot-${inputs_kernel}-*.tar.gz -l 2>/dev/null | grep "^-" | wc -l) -ge 1 ]; then
+        build_boot=$(ls ${P4_PATH}/boot-${inputs_kernel}-*.tar.gz | head -n 1) && build_boot=${build_boot##*/}
         custom_kernel_name=${build_boot/boot-/} && custom_kernel_name=${custom_kernel_name/.tar.gz/}
         echo -e "custom_kernel_name: ${custom_kernel_name}"
 
@@ -196,17 +196,17 @@ else
     die "Please upload the kernel files to [ ${P4_PATH} ], then run [ $0 ] again."
 fi
 
-MODULES_OLD=$(ls /lib/modules/ 2>/dev/null)
-VERSION_OLD=$(echo ${MODULES_OLD} | grep -oE '^[1-9].[0-9]{1,3}' 2>/dev/null)
-VERSION_ver=${VERSION_OLD%%.*}
-VERSION_maj=${VERSION_OLD##*.}
-if [ ${VERSION_ver} -eq "5" ]; then
-    if [ "${VERSION_maj}" -ge "10" ]; then
+modules_old=$(ls /lib/modules/ 2>/dev/null)
+version_old=$(echo ${modules_old} | grep -oE '^[1-9].[0-9]{1,3}' 2>/dev/null)
+version_ver=${version_old%%.*}
+version_maj=${version_old##*.}
+if [ ${version_ver} -eq "5" ]; then
+    if [ "${version_maj}" -ge "10" ]; then
         V510=1
     else
         V510=0
     fi
-elif [ ${VERSION_ver} -gt "5" ]; then
+elif [ ${version_ver} -gt "5" ]; then
     V510=1
 else
     V510=0
@@ -220,7 +220,7 @@ if [ "${V510}" -lt "${K510}" ]; then
     if [[ -n "${UBOOT_OVERLOAD}" ]]; then
         if [[ ! -s "/boot/${UBOOT_OVERLOAD}" ]]; then
             echo -e "Try to download the ${UBOOT_OVERLOAD} file from the server."
-            GITHUB_UBOOT_OVERLOAD="${GITHUB_RAW}/amlogic-u-boot/${UBOOT_OVERLOAD}"
+            GITHUB_UBOOT_OVERLOAD="${depends_repo}/amlogic-u-boot/${UBOOT_OVERLOAD}"
             #echo -e "UBOOT_OVERLOAD: ${GITHUB_UBOOT_OVERLOAD}"
             wget -c "${GITHUB_UBOOT_OVERLOAD}" -O "/boot/${UBOOT_OVERLOAD}" >/dev/null 2>&1 && sync
             if [[ "$?" -eq "0" && -s "/boot/${UBOOT_OVERLOAD}" ]]; then
@@ -236,10 +236,10 @@ if [ "${V510}" -lt "${K510}" ]; then
     fi
 
     # Check ${MAINLINE_UBOOT}
-    if [[ -n "${MAINLINE_UBOOT}" && "${AUTO_MAINLINE_UBOOT}" == "yes" ]]; then
+    if [[ -n "${MAINLINE_UBOOT}" && "${auto_mainline_uboot}" == "yes" ]]; then
         if [[ ! -s "${MAINLINE_UBOOT}" ]]; then
             echo -e "Try to download the MAINLINE_UBOOT file from the server."
-            GITHUB_MAINLINE_UBOOT="${GITHUB_RAW}/common-files/files/usr${MAINLINE_UBOOT}"
+            GITHUB_MAINLINE_UBOOT="${depends_repo}/common-files/files/usr${MAINLINE_UBOOT}"
             #echo -e "MAINLINE_UBOOT: ${GITHUB_MAINLINE_UBOOT}"
             [ -d "/lib/u-boot" ] || mkdir -p /lib/u-boot
             wget -c "${GITHUB_MAINLINE_UBOOT}" -O "${MAINLINE_UBOOT}" >/dev/null 2>&1 && sync
@@ -261,7 +261,7 @@ if [ "${V510}" -lt "${K510}" ]; then
     fi
 
     # Write Mainline bootloader
-    if [[ -f "${MAINLINE_UBOOT}" && "${AUTO_MAINLINE_UBOOT}" == "yes" ]]; then
+    if [[ -f "${MAINLINE_UBOOT}" && "${auto_mainline_uboot}" == "yes" ]]; then
         echo -e "Write Mainline bootloader: [ ${MAINLINE_UBOOT} ] to [ /dev/${EMMC_NAME} ]"
         dd if=${MAINLINE_UBOOT} of=/dev/${EMMC_NAME} bs=1 count=442 conv=fsync
         dd if=${MAINLINE_UBOOT} of=/dev/${EMMC_NAME} bs=512 skip=1 seek=1 conv=fsync
@@ -322,13 +322,13 @@ fi
 echo -e "02.01 Unpack [ ${build_boot} ] complete."
 sleep 3
 
-# 02 for /boot/dtb/amlogic/*
+# 02. for /boot/dtb/amlogic/*
 tar -xzf ${P4_PATH}/${build_dtb} -C /boot/dtb/amlogic && sync
 [ "$(ls /boot/dtb/amlogic -l 2>/dev/null | grep "^-" | wc -l)" -ge "10" ] || die "/boot/dtb/amlogic file is missing."
 echo -e "02.02 Unpack [ ${build_dtb} ] complete."
 sleep 3
 
-# 03 for /lib/modules/*
+# 03. for /lib/modules/*
 rm -rf /lib/modules/* 2>/dev/null && sync
 tar -xzf ${P4_PATH}/${build_modules} -C /lib/modules && sync
 (cd /lib/modules/${custom_kernel_name} && echo "build source" | xargs rm -f)
@@ -336,7 +336,7 @@ tar -xzf ${P4_PATH}/${build_modules} -C /lib/modules && sync
 echo -e "02.03 Unpack [ ${build_modules} ] complete."
 sleep 3
 
-# 04 for /usr/local/include/*
+# 04. for /usr/local/include/*
 if [[ -n "${build_header}" && -f "${P4_PATH}/${build_header}" ]]; then
     rm -rf /usr/local/include/* 2>/dev/null && sync
     tar -xzf ${P4_PATH}/${build_header} -C /usr/local && sync
@@ -344,14 +344,14 @@ if [[ -n "${build_header}" && -f "${P4_PATH}/${build_header}" ]]; then
     sleep 3
 fi
 
-# Delete kernel files
+# 05. Delete kernel files
 rm -f ${P4_PATH}/*${custom_kernel_name}*.tar.gz 2>/dev/null
 
-# 04 Update
-sed -i '/KERNEL_VERSION/d' ${ENV_ARMBIAN_FILE} 2>/dev/null
-echo "KERNEL_VERSION='${kernel_version}'" >>${ENV_ARMBIAN_FILE} 2>/dev/null
-sed -i '/K510/d' ${ENV_ARMBIAN_FILE} 2>/dev/null
-echo "K510='${K510}'" >>${ENV_ARMBIAN_FILE} 2>/dev/null
+# 06. Update
+sed -i '/KERNEL_VERSION/d' ${ophub_release_file} 2>/dev/null
+echo "KERNEL_VERSION='${kernel_version}'" >>${ophub_release_file} 2>/dev/null
+sed -i '/K510/d' ${ophub_release_file} 2>/dev/null
+echo "K510='${K510}'" >>${ophub_release_file} 2>/dev/null
 
 sync
 wait
