Unified error output messages

diff --git a/build-armbian/common-files/files/usr/sbin/armbian-install b/build-armbian/common-files/files/usr/sbin/armbian-install
--- a/build-armbian/common-files/files/usr/sbin/armbian-install
+++ b/build-armbian/common-files/files/usr/sbin/armbian-install
@@ -37,8 +37,12 @@ DEV_EMMC="/dev/${install_emmc}"
 echo "DEV_EMMC: ${DEV_EMMC}"
 
 #Check if writing to EMMC is supported
-MODULES_NOW=$(ls /usr/lib/modules/ 2>/dev/null)
-VERSION_NOW=$(echo ${MODULES_NOW} | grep -oE '^[1-9].[0-9]{1,3}' 2>/dev/null)
+VERSION_NOW=$(ls /usr/lib/modules/ 2>/dev/null | sort -rV | head -n 1 | grep -oE '^[1-9].[0-9]{1,3}.[0-9]+')
+if [ -z "${VERSION_NOW}" ]; then
+    echo "Failed to query the current version."
+    exit 1
+fi
+
 echo "This Kernel [ ${VERSION_NOW} ]"
 
 k510_ver=$(echo "${VERSION_NOW}" | cut -d '.' -f1)
