armbian-ddbr: Adjust code indentation

diff --git a/build-armbian/common-files/files/usr/sbin/armbian-ddbr b/build-armbian/common-files/files/usr/sbin/armbian-ddbr
--- a/build-armbian/common-files/files/usr/sbin/armbian-ddbr
+++ b/build-armbian/common-files/files/usr/sbin/armbian-ddbr
@@ -29,15 +29,15 @@ mydevice_name=$(cat /proc/device-tree/model | tr -d '\000')
 # Find the EMMC drive
 emmc="$(lsblk -l -o NAME | grep -oE "mmcblk[0-9]boot0" | sort | uniq | sed "s/boot0//g")"
 if [[ "${emmc}" == "" ]]; then
-	echo "No emmc can be found to install the openwrt system!"
-	exit 1
+    echo "No emmc can be found to install the openwrt system!"
+    exit 1
 fi
 
 # Find the partition where root is located
 root_devname=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print substr($3, 1, length($3)-2)}')
 if lsblk -l | grep -E "^${root_devname}boot0" >/dev/null; then
-	echo "you are running in emmc mode, please boot system with usb or tf card!"
-	exit 1
+    echo "you are running in emmc mode, please boot system with usb or tf card!"
+    exit 1
 fi
 
 # Check the output path
@@ -50,36 +50,36 @@ dev_intsize="$(fdisk -s /dev/${emmc})"
 
 # Check the remaining space
 do_checkspace() {
-	remaining_space="$(df -hT ${out_path} | grep '/dev/' | awk '{print $5}' | sed 's/.$//' | awk -F "." '{print $1}')"
-	if [ -z "$(echo "${remaining_space}" | sed -n "/^[0-9]\+$/p")" ]; then
-		echo -e "${ERROR} The path is not available, the remaining space cannot be obtained."
-		exit 1
-	fi
-	if [[ "${remaining_space}" -lt "${need_space}" ]]; then
-		echo -e "${ERROR} The remaining space is [ ${remaining_space} ] GB."
-		echo -e "It is recommended that the remaining space should not be less than [ ${need_space} ] GB."
-		echo -e "Please use the [ armbian-tf ] command to extended partition first."
-		exit 1
-	fi
+    remaining_space="$(df -hT ${out_path} | grep '/dev/' | awk '{print $5}' | sed 's/.$//' | awk -F "." '{print $1}')"
+    if [ -z "$(echo "${remaining_space}" | sed -n "/^[0-9]\+$/p")" ]; then
+        echo -e "${ERROR} The path is not available, the remaining space cannot be obtained."
+        exit 1
+    fi
+    if [[ "${remaining_space}" -lt "${need_space}" ]]; then
+        echo -e "${ERROR} The remaining space is [ ${remaining_space} ] GB."
+        echo -e "It is recommended that the remaining space should not be less than [ ${need_space} ] GB."
+        echo -e "Please use the [ armbian-tf ] command to extended partition first."
+        exit 1
+    fi
 }
 
 # Backup the emmc system
 do_backup() {
-	echo -e "${STEPS} Start to backup the system in emmc."
-	do_checkspace
-	echo -e "Saving and Compressing [ /dev/${emmc} ] to [ ${out_path}/${ddbr_image} ], Please wait..."
-	rm -f ${out_path}/${ddbr_image} 2>/dev/null && sync
-	dd if=/dev/${emmc} | pv -s ${dev_intsize}"K" | gzip >${out_path}/${ddbr_image}
-	[ "$?" -eq "0" ] && sync && echo -e "${SUCCESS} Backup is complete."
+    echo -e "${STEPS} Start to backup the system in emmc."
+    do_checkspace
+    echo -e "Saving and Compressing [ /dev/${emmc} ] to [ ${out_path}/${ddbr_image} ], Please wait..."
+    rm -f ${out_path}/${ddbr_image} 2>/dev/null && sync
+    dd if=/dev/${emmc} | pv -s ${dev_intsize}"K" | gzip >${out_path}/${ddbr_image}
+    [ "$?" -eq "0" ] && sync && echo -e "${SUCCESS} Backup is complete."
 }
 
 # Restore the emmc system
 do_restore() {
-	echo -e "${STEPS} Start to restore the system in emmc."
-	[ ! -f ${out_path}/${ddbr_image} ] && echo -e "${ERROR} The [ ${out_path}/${ddbr_image} ] File not found." && exit 1
-	echo -e "Restoring [ ${out_path}/${ddbr_image} ] to [ /dev/${emmc} ], Please wait..."
-	gunzip -c ${out_path}/${ddbr_image} | pv -s ${dev_intsize}"K" | dd of=/dev/${emmc}
-	[ "$?" -eq "0" ] && sync && echo -e "${SUCCESS} Restore is complete."
+    echo -e "${STEPS} Start to restore the system in emmc."
+    [ ! -f ${out_path}/${ddbr_image} ] && echo -e "${ERROR} The [ ${out_path}/${ddbr_image} ] File not found." && exit 1
+    echo -e "Restoring [ ${out_path}/${ddbr_image} ] to [ /dev/${emmc} ], Please wait..."
+    gunzip -c ${out_path}/${ddbr_image} | pv -s ${dev_intsize}"K" | dd of=/dev/${emmc}
+    [ "$?" -eq "0" ] && sync && echo -e "${SUCCESS} Restore is complete."
 }
 
 # Output device information
@@ -93,7 +93,7 @@ echo -e "${INFO} The ddbr file path: [ ${out_path}/${ddbr_image} ]\n"
 echo -ne "${OPT} Do you want to backup or restore? Backup=(b) Restore=(r): "
 read br
 case ${br} in
-	b | B | backup) do_backup ;;
-	r | R | restore) do_restore ;;
-	*) exit 0 ;;
+    b | B | backup) do_backup ;;
+    r | R | restore) do_restore ;;
+    *) exit 0 ;;
 esac
