Update workflows name

diff --git a/.github/workflows/build-armbian-using-official-image.yml b/.github/workflows/build-armbian-using-official-image.yml
--- a/.github/workflows/build-armbian-using-official-image.yml
+++ b/.github/workflows/build-armbian-using-official-image.yml
@@ -1,25 +1,18 @@
 #==========================================================================
-# Description: Build Armbian
+# Description: Build Armbian using official files
 # Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
-# Copyright (C) 2024 https://github.com/dy008/amlogic-s9xxx-armbian
 #==========================================================================
 
-name: Build Homeassistant
+name: Build Armbian using official files
 
 on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      set_release:
-        description: "Select OS Release."
+      armbian_url:
+        description: "Set Armbian file path."
         required: false
-        default: "bookworm"
-        type: choice
-        options:
-          - jammy
-          - noble
-          - bookworm
-          - bullseye
+        default: ""
       armbian_board:
         description: "Select device board."
         required: false
@@ -217,7 +210,7 @@ on:
           - dev
           - beta
       armbian_fstype:
-        description: "Select armbian rootfs type."
+        description: "Set armbian rootfs type."
         required: false
         default: "ext4"
         type: choice
@@ -235,15 +228,15 @@ on:
       builder_name:
         description: "Set Armbian builder signature."
         required: false
-        default: "dy008"
+        default: "ophub"
         type: choice
         options:
           - ophub
-          - dy008
+          - angel
+          - yourname
 
 env:
   TZ: America/New_York
-  ROOTFS_SCRIPT: compile-kernel/tools/script/docker/build_armbian_rootfs_file.sh
 
 jobs:
   build:
@@ -294,65 +287,51 @@ jobs:
           sudo chown -R runner.runner /builder
           df -Th
 
-      - name: Download source code
+      - name: Set download address
         id: down
         working-directory: /builder
-        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
         run: |
-          df -hT ${PWD}
-          git clone -q --single-branch --depth=1 --branch=main https://github.com/armbian/build.git build
+          # Get the url of the rebuild armbian file
+          armbian_url="${{ inputs.armbian_url }}"
+          if  [[ -z "${armbian_url}" ]]; then
+              armbian_site="https://armbian.tnahosting.net/dl/odroidn2/archive/"
+              armbian_name="Armbian.*jammy.*.img.xz"
+              armbian_file=$(curl -s "${armbian_site}" | grep -oE "${armbian_name}" | head -n 1)
+              if [[ -n "${armbian_file}" ]]; then
+                  armbian_url="${armbian_site}${armbian_file}"
+              else
+                  echo -e "Invalid download path: [ ${armbian_site} ]"
+                  exit 1
+              fi
+          fi
+          echo "ARMBIAN_URL=${armbian_url}" >> ${GITHUB_ENV}
+
+          # Get the release name of the rebuild armbian file
+          set_release=""
+          ARR_RELEASE=("jammy" "focal" "bullseye" "buster" "sid")
+          i=1
+          for r in ${ARR_RELEASE[*]}; do
+              if [[ "${armbian_url}" == *"${r}"* ]]; then
+                  set_release="_${r}"
+                  break
+              fi
+              let i++
+          done
+
+          mkdir -p /builder/build
           ln -sf /builder/build ${GITHUB_WORKSPACE}/build
           ln -sf /builder/build /home/runner/work/_actions/ophub/amlogic-s9xxx-armbian/main/build
-          # 下载扩展的安装homeasssistant脚本
-          wget -P ./build/extensions https://raw.githubusercontent.com/armbian/os/main/userpatches/extensions/docker-ce.sh
-          wget -P ./build/extensions https://raw.githubusercontent.com/armbian/os/main/userpatches/extensions/ha.sh
-          # 修改ha.sh脚本中的命令以停止internet host IP地址检测
-          sed -i "/sed -i \"\/update-grub\/d\"/a\sed -i \"s\/while ! ping\/while   ping\/\" homeassistant-supervised/DEBIAN/postinst" ./build/extensions/ha.sh
-          # 在ha.sh的chroot_sdcard_apt_get_install方法里添加缺少的依赖包
-          more_ha_deps="systemd-timesyncd"
-          sed -i "s|systemd-journal-remote |systemd-journal-remote ${more_ha_deps} |g" ./build/extensions/ha.sh
+
+          sudo timedatectl set-timezone "${TZ}"
+          echo "build_tag=Armbian${set_release}_${{ inputs.armbian_storage }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
           echo "status=success" >> ${GITHUB_OUTPUT}
-
-      - name: Compile Armbian [ ${{ inputs.set_release }} ]
-        id: compile
-        working-directory: /builder
-        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
-        run: |
-          # Compile method and parameter description: https://docs.armbian.com/Developer-Guide_Build-Options
-          cd build/
-              ./compile.sh RELEASE=${{ inputs.set_release }} BOARD=odroidn2 BRANCH=current ENABLE_EXTENSIONS="ha" BUILD_MINIMAL=no \
-                           BUILD_ONLY=default HOST=armbian BUILD_DESKTOP=no EXPERT=yes KERNEL_CONFIGURE=no \
-                           COMPRESS_OUTPUTIMAGE="sha" SHARE_LOG=yes
-          echo "status=success" >> ${GITHUB_OUTPUT}
-
-      - name: Organize files and clear space
-        id: clean
-        if: ${{ steps.compile.outputs.status }} == 'success' && !cancelled()
-        run: |
-          # Organize and keep essential files, delete unnecessary files
-          chmod +x ${ROOTFS_SCRIPT}
-          ${ROOTFS_SCRIPT} -v ${{ inputs.set_release }} -s true -c true -k true
-
-          # Output cleaning result information
-          df -hT ${PWD}
-          echo "build_tag=Armbian_HassIoSupervisor_${{ inputs.set_release }}_${{ inputs.armbian_storage }}_$(date +"%Y.%m")" >> ${GITHUB_OUTPUT}
-          echo "status=success" >> ${GITHUB_OUTPUT}
-
-      - name: Upload Armbian image to Release
-        uses: ncipollo/release-action@main
-        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
-        with:
-          tag: ${{ steps.clean.outputs.build_tag }}
-          artifacts: build/output/images/*
-          allowUpdates: true
-          token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Rebuild Armbian
         uses: ophub/amlogic-s9xxx-armbian@main
-        if: ${{ steps.clean.outputs.status }} == 'success' && !cancelled()
+        if: ${{ env.ARMBIAN_URL }} != '' && !cancelled()
         with:
           build_target: armbian
-          armbian_path: build/output/images/*.img.gz
+          armbian_path: ${{ env.ARMBIAN_URL }}
           armbian_board: ${{ inputs.armbian_board }}
           armbian_kernel: ${{ inputs.armbian_kernel }}
           auto_kernel: ${{ inputs.auto_kernel }}
@@ -361,18 +340,18 @@ jobs:
           armbian_fstype: ${{ inputs.armbian_fstype }}
           builder_name: ${{ inputs.builder_name }}
 
-      - name: Upload Rebuild image to Release
+      - name: Upload Armbian image to Release
         uses: ncipollo/release-action@main
         if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
         with:
-          tag: ${{ steps.clean.outputs.build_tag }}
+          tag: ${{ steps.down.outputs.build_tag }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           removeArtifacts: false
           replacesArtifacts: true
           token: ${{ secrets.GITHUB_TOKEN }}
           body: |
-            ### Armbian For Homeassistant Supervisor Image information
+            ### Armbian Image information
             - Default username: root
             - Default password: 1234
             - Install command: armbian-install
