Add armbian rebuild example

diff --git a/.github/workflows/rebuild-armbian.yml b/.github/workflows/rebuild-armbian.yml
--- a/.github/workflows/rebuild-armbian.yml
+++ b/.github/workflows/rebuild-armbian.yml
@@ -1,14 +1,18 @@
 #========================================================================================================================
 # Description: Build Armbian For Amlogic S9xxx STB
 # Copyright (C) 2021 https://github.com/ophub/amlogic-s9xxx-armbian
-# Cron: min (0 - 59) / hour (0 - 23) / day of month (1 - 31) / month (1 - 12) / day of week (0 - 6)(Sunday - Saturday)
 #========================================================================================================================
 
-name: Use Releases file to build armbian
+name: Rebuild armbian
 
 on:
   repository_dispatch:
   workflow_dispatch:
+    inputs:
+      armbian_url:
+        description: "Enter armbian path"
+        required: false
+        default: ""
 
 env:
   UPLOAD_FIRMWARE: false
@@ -34,37 +38,43 @@ jobs:
           sudo -E apt-get -qq autoremove --purge
           sudo -E apt-get -qq clean
           sudo timedatectl set-timezone "$TZ"
+          sudo mkdir -p /workdir
+          sudo chown $USER:$GROUPS /workdir
+          if  [[ -n "${{ github.event.inputs.armbian_url }}" ]]; then
+              armbian_url="${{ github.event.inputs.armbian_url }}"
+          else
+              armbian_down="https://armbian.tnahosting.net/dl/lepotato/archive/"
+              armbian_file=$(curl -s ${armbian_down} | grep -oE Armbian.*buster.*.img.xz | head -n 1)
+              if [ -n "${armbian_file}" ]; then
+                  armbian_url="${armbian_down}/${armbian_file}"
+              else
+                  echo -e "Invalid download path: [ ${armbian_down} ]"
+                  exit 1
+              fi
+          fi
+          echo "ARMBIAN_URL=${armbian_url}" >> $GITHUB_ENV
           echo "COMPILE_STARTINGTIME=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
 
-      - name: Rebuild Armbian for amlogic s9xxx
-        id: rebuild
-        if: (!cancelled())
-        run: |
-          [ -d build/output/images ] || mkdir -p build/output/images
-          curl -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "Armbian_Aml_buster_.*/Armbian_.*-trunk_.*.img.gz" | head -n 1 > DOWNLOAD_ARMBIAN
-          [ -s DOWNLOAD_ARMBIAN ] && wget -q -P build/output/images https://github.com/${GITHUB_REPOSITORY}/releases/download/$(cat DOWNLOAD_ARMBIAN)
-          cd build/output/images/ && gzip -df *.img.gz && sync && cd ../../../
-          sudo chmod +x rebuild
-          sudo ./rebuild -d -b s922x_s922x-n2_s905x3_s905x2_s905d_s912_s912-t95z -k 5.10.80_5.4.160
-          sudo ./rebuild -d -b s905x_s905w -k 5.4.160
-          cd ./build/output/images && sudo gzip *.img && sync
-          echo "FILEPATH=$PWD" >> $GITHUB_ENV
-          echo "FILE_DATE=$(date +"%Y.%m.%d.%H%M")" >> $GITHUB_ENV
-          echo "::set-output name=status::success"
-
-      - name: Upload artifact to Actions
-        uses: kittaakos/upload-artifact-as-is@master
-        if: steps.rebuild.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
+      - name: Rebuild Armbian for Amlogic s9xxx
+        uses: ophub/amlogic-s9xxx-armbian@main
         with:
-          path: ${{ env.FILEPATH }}/
+          armbian_path: ${{ env.ARMBIAN_URL }}
+          armbian_soc: s905d_s905x3
+          armbian_kernel: 5.10.80_5.4.160
+
+      - name: Upload Armbian image to Actions
+        uses: kittaakos/upload-artifact-as-is@master
+        if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
+        with:
+          path: ${{ env.PACKAGED_OUTPUTPATH }}/
 
       - name: Upload Armbian image to Release
         id: release
         uses: ncipollo/release-action@v1
-        if: steps.rebuild.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
+        if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_RELEASE == 'true' && !cancelled()
         with:
-          tag: Armbian_Aml_buster_${{ env.FILE_DATE }}
-          artifacts: ${{ env.FILEPATH }}/*
+          tag: Armbian_Aml_buster_${{ env.PACKAGED_OUTPUTDATE }}
+          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GITHUB_TOKEN }}
           body: |
