Remove desktop options

diff --git a/.github/workflows/use-releases-file-to-build.yml b/.github/workflows/use-releases-file-to-build.yml
--- a/.github/workflows/use-releases-file-to-build.yml
+++ b/.github/workflows/use-releases-file-to-build.yml
@@ -9,7 +9,7 @@ on:
   repository_dispatch:
   workflow_dispatch:
     inputs:
-      sel_tags_keywords:
+      set_release:
         description: "Select OS Release."
         required: false
         default: "jammy"
@@ -70,6 +70,10 @@ on:
         options:
           - ext4
           - btrfs
+      armbian_sign:
+        description: "Set armbian custom name."
+        required: false
+        default: ""
 
 env:
   TZ: America/New_York
@@ -102,32 +106,21 @@ jobs:
         if: (!cancelled())
         run: |
           armbian_buildpath="build/output/images"
-          [ -d "${armbian_buildpath}" ] || mkdir -p "${armbian_buildpath}"
+          [[ -d "${armbian_buildpath}" ]] || mkdir -p "${armbian_buildpath}"
           down_repo="https://api.github.com/repos/${GITHUB_REPOSITORY}/releases"
-          down_path="Armbian_Aml_${{ github.event.inputs.sel_tags_keywords }}.*/Armbian_.*-trunk_.*.img.gz"
-          #
+          down_path="Armbian_Aml_${{ github.event.inputs.set_release }}.*/Armbian_.*-trunk_.*.img.gz"
+
           # down_filename: Armbian_Aml_bullseye_gnome_desktop_05.17.1924/Armbian_22.05.0-trunk_Odroidn2_bullseye_current_5.10.110.img.gz
           down_filename="$(curl -s "${down_repo}" | grep -oE "${down_path}" | head -n 1)"
           down_file="https://github.com/${GITHUB_REPOSITORY}/releases/download/${down_filename}"
-          [ -z "${down_file}" ] && echo "Invalid download file." && exit 1
+          [[ -z "${down_file}" ]] && echo "Invalid download file." && exit 1
           wget -q -P "${armbian_buildpath}" "${down_file}" && sync
           cd "${armbian_buildpath}" && gzip -df *.img.gz && sync
-          #
-          # down_tags: Armbian_Aml_bullseye_gnome_desktop
-          down_tags="${down_filename%%/*}" && down_tags="${down_tags%_*}"
-          echo "ARMBIAN_TAGS=${down_tags}" >> $GITHUB_ENV
-          #
-          # down_release: bullseye
-          down_release="$(echo ${down_tags} | cut -d"_" -f3)"
-          echo "ARMBIAN_RELEASE=${down_release}" >> $GITHUB_ENV
-          #
-          # down_edition: gnome_desktop
-          down_edition="$(echo ${down_tags} | cut -d"_" -f4-)"
-          echo "ARMBIAN_DESKTOP_OPT=${down_edition}" >> $GITHUB_ENV
-          #
+
+          echo "ARMBIAN_RELEASE=${{ github.event.inputs.set_release }}" >> $GITHUB_ENV
           echo "::set-output name=status::success"
 
-      - name: Rebuild Armbian [ Release is ${{ env.ARMBIAN_RELEASE }} / Edition is ${{ env.ARMBIAN_DESKTOP_OPT }} ]
+      - name: Rebuild Armbian [ Release is ${{ env.ARMBIAN_RELEASE }} ]
         uses: ophub/amlogic-s9xxx-armbian@main
         if: steps.down.outputs.status == 'success' && !cancelled()
         with:
@@ -138,13 +131,13 @@ jobs:
           auto_kernel: ${{ github.event.inputs.auto_kernel }}
           armbian_size: ${{ github.event.inputs.armbian_size }}
           armbian_fstype: ${{ github.event.inputs.armbian_fstype }}
-          armbian_sign: _${{ env.ARMBIAN_DESKTOP_OPT }}
+          armbian_sign: ${{ github.event.inputs.armbian_sign }}
 
       - name: Upload Armbian image to Release
         uses: ncipollo/release-action@main
         if: env.PACKAGED_STATUS == 'success' && !cancelled()
         with:
-          tag: ${{ env.ARMBIAN_TAGS }}_${{ env.PACKAGED_OUTPUTDATE }}
+          tag: Armbian_Aml_${{ env.ARMBIAN_RELEASE }}_${{ env.PACKAGED_OUTPUTDATE }}
           artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
           allowUpdates: true
           token: ${{ secrets.GH_TOKEN }}
@@ -155,4 +148,3 @@ jobs:
             Default password: 1234
             Install command: armbian-install
             Update command: armbian-update
-            Edition: ${{ env.ARMBIAN_DESKTOP_OPT }}
